// Generated by tools/codegen/generate_metadata.py; source-sha256: 8408499480d1c7bf78f9eab8889b4ae2d867a536c8507606205935a6b70c05ff.
// SPDX-FileCopyrightText: 2026 Jules C
// SPDX-License-Identifier: MIT
#import <Foundation/Foundation.h>
@class FacManCommandDefinition;
NSArray<FacManCommandDefinition *> *FacManGeneratedCommandCatalog(void);
NSDictionary<NSString *, id> *FacManGeneratedPayload(FacManCommandDefinition *command, NSDictionary<NSString *, NSString *> *inputs, NSString **error);
