// Generated by tools/codegen/generate_metadata.py; source-sha256: 42d82855d655c06072b6ba4b419be8ac2558d085875f3f0ecf8506328fd6e780.
// SPDX-FileCopyrightText: 2026 Jules C
// SPDX-License-Identifier: MIT
#import <Foundation/Foundation.h>
@class FacManCommandDefinition;
#ifdef __cplusplus
extern "C" {
#endif
NSArray<FacManCommandDefinition *> *FacManGeneratedCommandCatalog(void);
NSDictionary<NSString *, id> *FacManGeneratedPayload(FacManCommandDefinition *command, NSDictionary<NSString *, NSString *> *inputs, NSString **error);
NSString *FacManGeneratedSetupWorkflowJSON(void);
NSString *FacManGeneratedSetupWorkflowText(void);
#ifdef __cplusplus
}
#endif
