// Generated by tools/codegen/generate_metadata.py; source-sha256: 671764ee966fe44d269d6787664049383ff461152616762b4312b0a1789abfdb.
// SPDX-FileCopyrightText: 2026 Jules C
// SPDX-License-Identifier: MIT
#import <Foundation/Foundation.h>
@class FacManCommandDefinition;
NSArray<FacManCommandDefinition *> *FacManGeneratedCommandCatalog(void);
NSDictionary<NSString *, id> *FacManGeneratedPayload(FacManCommandDefinition *command, NSDictionary<NSString *, NSString *> *inputs, NSString **error);
NSString *FacManGeneratedSetupWorkflowJSON(void);
NSString *FacManGeneratedSetupWorkflowText(void);
