// Generated by tools/generate_classic_preview_rpc.py; do not edit.
// SPDX-FileCopyrightText: 2026 Jules C
// SPDX-License-Identifier: MIT

#pragma once

#include <glib.h>

gchar *facman_record_text(const gchar *document, const gchar *key);
gboolean facman_record_boolean(const gchar *document, const gchar *key);
gboolean facman_record_empty_array(const gchar *document, const gchar *key);
gchar *facman_payload_text(const gchar *document, const gchar *key);
gboolean facman_payload_boolean(const gchar *document, const gchar *key);
gboolean facman_payload_empty_array(const gchar *document, const gchar *key);
gchar *facman_error_text(const gchar *document, const gchar *key);
gboolean facman_payload_recovery_required(const gchar *document);
gchar *facman_payload_recovery_text(const gchar *document, const gchar *key);
gchar *facman_instance_payload(const gchar *instance_id);
gchar *facman_recovery_payload(const gchar *transaction_id);
gchar *facman_create_instance_payload(
    const gchar *instance_id,
    const gchar *display_name,
    const gchar *install_id);
