// Generated by tools/codegen/generate_metadata.py; do not edit.
// release/index/version.v2.toml sha256: a28d257b66033514e7621e9c9818ac545e0ecddc638544fe4b32d60e1b536e1d
// SPDX-FileCopyrightText: 2026 Jules C
// SPDX-License-Identifier: MIT

#pragma once

#define FACMAN_GUI_PRODUCT_NAME "FacMan"
#define FACMAN_GUI_PRODUCT_ID "facman"
#define FACMAN_GUI_SEMVER "0.1.0-alpha.5"
#define FACMAN_GUI_CANONICAL_VERSION "facman-0.1.0-alpha.5"
#define FACMAN_GUI_APPLICATION_ID "io.github.julesc013.facman"
#define FACMAN_GUI_WINDOW_TITLE "FacMan \u2014 GTK 3 experimental \u00b7 0.1.0-alpha.5"
#define FACMAN_GUI_SETTINGS_EVIDENCE "FacMan 0.1.0-alpha.5 \u00b7 EXPLICIT EVIDENCE / DEVELOPMENT MODE \u00b7 unchanged fixtures \u00b7 no live Play authority"
#define FACMAN_GUI_SETTINGS_LIVE "FacMan 0.1.0-alpha.5 \u00b7 LIVE BACKEND MODE \u00b7 bounded process RPC \u00b7 backend-gated Play \u00b7 GTK experimental support lane"
