// Generated by tools/generate_classic_preview_rpc.py; do not edit.
// SPDX-FileCopyrightText: 2026 Jules C
// SPDX-License-Identifier: MIT

#pragma once

#include <glib.h>

gchar *facman_preview_generated_rpc_request(const gchar *workspace, const gchar *command);
