// Generated by tools/generate_classic_preview_rpc.py; do not edit.
// SPDX-FileCopyrightText: 2026 Jules C
// SPDX-License-Identifier: MIT

#include "generated_live_presentation.h"

#include <string.h>

static gchar *facman_generated_json_escape(const gchar *value)
{
    const guchar *cursor = (const guchar *)(value != NULL ? value : "");
    GString *escaped = g_string_new("");
    for (; *cursor != '\0'; ++cursor) {
        switch (*cursor) {
            case '"': g_string_append(escaped, "\\\""); break;
            case '\\': g_string_append(escaped, "\\\\"); break;
            case '\b': g_string_append(escaped, "\\b"); break;
            case '\f': g_string_append(escaped, "\\f"); break;
            case '\n': g_string_append(escaped, "\\n"); break;
            case '\r': g_string_append(escaped, "\\r"); break;
            case '\t': g_string_append(escaped, "\\t"); break;
            default:
                if (*cursor < 0x20)
                    g_string_append_printf(escaped, "\\u%04x", (unsigned int)*cursor);
                else
                    g_string_append_c(escaped, (gchar)*cursor);
                break;
        }
    }
    return g_string_free(escaped, FALSE);
}

static const gchar *facman_member_within(
    const gchar *begin,
    const gchar *end,
    const gchar *key)
{
    gchar *needle = g_strdup_printf("\"%s\"", key);
    const gchar *cursor = begin != NULL && end != NULL && end >= begin
        ? g_strstr_len(begin, end - begin, needle)
        : NULL;
    g_free(needle);
    if (cursor == NULL || (cursor = memchr(cursor, ':', end - cursor)) == NULL) return NULL;
    cursor++;
    while (cursor < end && g_ascii_isspace(*cursor)) cursor++;
    if (cursor >= end) return NULL;
    return cursor;
}

static const gchar *facman_document_end(const gchar *document)
{
    return document != NULL ? document + strlen(document) : NULL;
}

static const gchar *facman_scope_end(const gchar *start, const gchar *document_end)
{
    gchar opening;
    gchar closing;
    guint depth = 0;
    gboolean in_string = FALSE;
    gboolean escaped = FALSE;

    if (start == NULL || start >= document_end || (*start != '{' && *start != '[')) return NULL;
    opening = *start;
    closing = opening == '{' ? '}' : ']';
    for (const gchar *cursor = start; cursor < document_end; cursor++) {
        if (in_string) {
            if (escaped) escaped = FALSE;
            else if (*cursor == '\\') escaped = TRUE;
            else if (*cursor == '"') in_string = FALSE;
            continue;
        }
        if (*cursor == '"') in_string = TRUE;
        else if (*cursor == opening) depth++;
        else if (*cursor == closing && --depth == 0) return cursor + 1;
    }
    return NULL;
}

static const gchar *facman_scoped_member(
    const gchar *document,
    const gchar *scope_key,
    const gchar *key,
    const gchar **scope_end)
{
    const gchar *document_end = facman_document_end(document);
    const gchar *scope = facman_member_within(document, document_end, scope_key);
    const gchar *end = facman_scope_end(scope, document_end);
    if (scope_end != NULL) *scope_end = end;
    return end != NULL ? facman_member_within(scope, end, key) : NULL;
}

static gchar *facman_text(const gchar *cursor, const gchar *end)
{
    if (cursor == NULL || *cursor != '"') return g_strdup("");
    cursor++;
    GString *value = g_string_new("");
    while (cursor < end && *cursor != '"') {
        if (*cursor == '\\' && cursor + 1 < end) {
            cursor++;
            if (*cursor == 'n') g_string_append_c(value, '\n');
            else if (*cursor == 'r') g_string_append_c(value, '\r');
            else if (*cursor == 't') g_string_append_c(value, '\t');
            else g_string_append_c(value, *cursor);
        } else {
            g_string_append_c(value, *cursor);
        }
        cursor++;
    }
    return g_string_free(value, FALSE);
}

static const gchar *facman_recovery_member(
    const gchar *document,
    const gchar *key,
    const gchar **member_end)
{
    const gchar *document_end = facman_document_end(document);
    const gchar *payload = facman_member_within(document, document_end, "payload");
    const gchar *payload_end = facman_scope_end(payload, document_end);
    const gchar *transactions = facman_member_within(payload, payload_end, "transactions");
    const gchar *transactions_end = facman_scope_end(transactions, payload_end);
    const gchar *cursor = transactions != NULL ? transactions + 1 : NULL;
    while (cursor != NULL && transactions_end != NULL && cursor < transactions_end) {
        const gchar *transaction = memchr(cursor, '{', transactions_end - cursor);
        const gchar *transaction_end = facman_scope_end(transaction, transactions_end);
        if (transaction_end == NULL) break;
        gchar *state = facman_text(
            facman_member_within(transaction, transaction_end, "state"), transaction_end);
        gboolean terminal = g_strcmp0(state, "complete") == 0 || g_strcmp0(state, "refused") == 0 ||
            g_strcmp0(state, "rolled_back") == 0 || g_strcmp0(state, "cancelled") == 0;
        g_free(state);
        if (!terminal) {
            if (member_end != NULL) *member_end = transaction_end;
            return facman_member_within(transaction, transaction_end, key);
        }
        cursor = transaction_end;
    }
    if (member_end != NULL) *member_end = NULL;
    return NULL;
}

gchar *facman_record_text(const gchar *document, const gchar *key)
{
    const gchar *end = facman_document_end(document);
    return facman_text(facman_member_within(document, end, key), end);
}

gboolean facman_record_boolean(const gchar *document, const gchar *key)
{
    const gchar *end = facman_document_end(document);
    const gchar *cursor = facman_member_within(document, end, key);
    return cursor != NULL && g_str_has_prefix(cursor, "true");
}

gboolean facman_record_empty_array(const gchar *document, const gchar *key)
{
    const gchar *end = facman_document_end(document);
    const gchar *cursor = facman_member_within(document, end, key);
    if (cursor == NULL || *cursor != '[') return FALSE;
    cursor++;
    while (g_ascii_isspace(*cursor)) cursor++;
    return *cursor == ']';
}

gchar *facman_payload_text(const gchar *document, const gchar *key)
{
    const gchar *end = NULL;
    const gchar *cursor = facman_scoped_member(document, "payload", key, &end);
    return facman_text(cursor, end);
}

gboolean facman_payload_boolean(const gchar *document, const gchar *key)
{
    const gchar *cursor = facman_scoped_member(document, "payload", key, NULL);
    return cursor != NULL && g_str_has_prefix(cursor, "true");
}

gboolean facman_payload_empty_array(const gchar *document, const gchar *key)
{
    const gchar *end = NULL;
    const gchar *cursor = facman_scoped_member(document, "payload", key, &end);
    if (cursor == NULL || *cursor != '[') return FALSE;
    cursor++;
    while (cursor < end && g_ascii_isspace(*cursor)) cursor++;
    return cursor < end && *cursor == ']';
}

gchar *facman_error_text(const gchar *document, const gchar *key)
{
    const gchar *end = NULL;
    const gchar *cursor = facman_scoped_member(document, "error", key, &end);
    return facman_text(cursor, end);
}

gboolean facman_payload_recovery_required(const gchar *document)
{
    return facman_recovery_member(document, "state", NULL) != NULL;
}

gchar *facman_payload_recovery_text(const gchar *document, const gchar *key)
{
    const gchar *end = NULL;
    const gchar *cursor = facman_recovery_member(document, key, &end);
    return facman_text(cursor, end);
}

gchar *facman_instance_payload(const gchar *instance_id)
{
    gchar *escaped = facman_generated_json_escape(instance_id);
    gchar *payload = g_strdup_printf("{\"instance_id\":\"%s\"}", escaped);
    g_free(escaped);
    return payload;
}

gchar *facman_recovery_payload(const gchar *transaction_id)
{
    gchar *escaped = facman_generated_json_escape(transaction_id);
    gchar *payload = g_strdup_printf("{\"transaction_id\":\"%s\"}", escaped);
    g_free(escaped);
    return payload;
}

gchar *facman_create_instance_payload(
    const gchar *instance_id,
    const gchar *display_name,
    const gchar *install_id)
{
    gchar *escaped_id = facman_generated_json_escape(instance_id);
    gchar *escaped_name = facman_generated_json_escape(display_name);
    gchar *escaped_install = facman_generated_json_escape(install_id);
    gchar *payload = g_strdup_printf(
        "{\"instance_id\":\"%s\",\"display_name\":\"%s\",\"install_id\":\"%s\"}",
        escaped_id, escaped_name, escaped_install);
    g_free(escaped_install);
    g_free(escaped_name);
    g_free(escaped_id);
    return payload;
}
