// Generated by tools/generate_classic_preview_rpc.py; do not edit.
// SPDX-FileCopyrightText: 2026 Jules C
// SPDX-License-Identifier: MIT

#include "generated_rpc_request.h"

static gchar *facman_preview_json_escape(const gchar *value)
{
    const guchar *cursor = (const guchar *)(value != NULL ? value : "");
    GString *escaped = g_string_new("");
    for (; *cursor != '\0'; ++cursor) {
        switch (*cursor) {
            case '"': g_string_append(escaped, "\\\""); break;
            case '\\': g_string_append(escaped, "\\\\"); break;
            case '\b': g_string_append(escaped, "\\b"); break;
            case '\f': g_string_append(escaped, "\\f"); break;
            case '\n': g_string_append(escaped, "\\n"); break;
            case '\r': g_string_append(escaped, "\\r"); break;
            case '\t': g_string_append(escaped, "\\t"); break;
            default:
                if (*cursor < 0x20)
                    g_string_append_printf(escaped, "\\u%04x", (unsigned int)*cursor);
                else
                    g_string_append_c(escaped, (gchar)*cursor);
                break;
        }
    }
    return g_string_free(escaped, FALSE);
}

gchar *facman_preview_generated_rpc_request_with_payload(
    const gchar *workspace,
    const gchar *command,
    const gchar *payload_json,
    gboolean dry_run)
{
    gchar *escaped_workspace = facman_preview_json_escape(workspace);
    gchar *escaped_command = facman_preview_json_escape(
        command != NULL ? command : "product.inspect");
    gchar *request_id = g_strdup_printf(
        "gtk-preview-%" G_GINT64_FORMAT "-%08x", g_get_monotonic_time(), g_random_int());
    gchar *operation_id = g_strdup_printf("%s-operation", request_id);
    gchar *attempt_id = g_strdup_printf("%s-attempt", request_id);
    gchar *request = g_strdup_printf(
        "{\"schema\":\"facman.transport_request.v2\",\"protocol_version\":2,"
        "\"request_id\":\"%s\",\"operation_id\":\"%s\","
        "\"attempt_id\":\"%s\",\"workspace\":\"%s\","
        "\"command\":\"%s\",\"dry_run\":%s,\"payload\":%s}",
        request_id, operation_id, attempt_id, escaped_workspace, escaped_command,
        dry_run ? "true" : "false",
        payload_json != NULL && *payload_json != '\0' ? payload_json : "{}");
    g_free(escaped_workspace);
    g_free(escaped_command);
    g_free(request_id);
    g_free(operation_id);
    g_free(attempt_id);
    return request;
}

gchar *facman_preview_generated_rpc_request(const gchar *workspace, const gchar *command)
{
    return facman_preview_generated_rpc_request_with_payload(workspace, command, "{}", TRUE);
}
