// Generated by tools/codegen/generate_metadata.py; source-sha256: 99c9089598f5491d889a18e78d89ab726548b8c14e2d21c2270cdbd3d8e26bb0.
// SPDX-FileCopyrightText: 2026 Jules C
// SPDX-License-Identifier: MIT

using System;
using System.Collections.Generic;

namespace FacMan.WinForms
{
    public static class GeneratedCommandCatalog
    {
        private static readonly IList<CommandDefinition> Commands = Build();

        public static IList<CommandDefinition> All() { return Commands; }

        public static CommandDefinition Find(string commandId)
        {
            foreach (CommandDefinition command in Commands)
                if (String.Equals(command.Id, commandId, StringComparison.Ordinal)) return command;
            throw new CommandValidationException("Unknown command id: " + commandId);
        }

        public static IDictionary<string, object> BuildPayload(CommandDefinition command, IDictionary<string, string> inputs)
        {
            Dictionary<string, object> payload = new Dictionary<string, object>();
            foreach (CommandInput input in command.Inputs)
            {
                string value;
                bool present = inputs.TryGetValue(input.Key, out value) && !String.IsNullOrWhiteSpace(value);
                if (input.Required && !present) throw new CommandValidationException("Missing required input: " + input.Key);
                if (!present) continue;
                value = value.Trim();
                if (input.Type == "string_array")
                {
                    List<string> values = new List<string>();
                    foreach (string part in value.Split(new char[] { '\r', '\n' }, StringSplitOptions.RemoveEmptyEntries))
                        if (!String.IsNullOrWhiteSpace(part)) values.Add(part.Trim());
                    payload[input.RequestField] = values;
                }
                else payload[input.RequestField] = value;
            }
            return payload;
        }

        private static IList<CommandDefinition> Build()
        {
            List<CommandDefinition> commands = new List<CommandDefinition>();
            commands.Add(new CommandDefinition(
                "capabilities.inspect", "Capabilities",
                "Capabilities Inspect", "capabilities.inspect",
                CommandStatus.Implemented, "Run facman capabilities inspect --json", "",
                "command.capabilities.inspect.title", "command.capabilities.inspect.description",
                "available", "read_only",
                new string[] { "workspace_read" },
                new CommandInput[] {  },
                "[]",
                "[{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "capabilities_inspect"));
            commands.Add(new CommandDefinition(
                "dev.benchmark", "Dev",
                "Dev Benchmark", "dev.benchmark",
                CommandStatus.NotSupportedWithReason, "Run facman dev benchmark --json", "execution_not_enabled",
                "command.dev.benchmark.title", "command.dev.benchmark.description",
                "unavailable_until_isolation_proof", "process_execution",
                new string[] { "process_execute" },
                new CommandInput[] {  },
                "[]",
                "[{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "dev_benchmark"));
            commands.Add(new CommandDefinition(
                "dev.bug_report", "Dev",
                "Dev Bug Report", "dev.bug_report",
                CommandStatus.Implemented, "Run facman dev bug-report --json", "",
                "command.dev.bug_report.title", "command.dev.bug_report.description",
                "available", "read_only",
                new string[] { "workspace_read" },
                new CommandInput[] {  },
                "[]",
                "[{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "dev_bug_report"));
            commands.Add(new CommandDefinition(
                "dev.dump_data", "Dev",
                "Dev Dump Data", "dev.dump_data",
                CommandStatus.NotSupportedWithReason, "Run facman dev dump-data --json", "execution_not_enabled",
                "command.dev.dump_data.title", "command.dev.dump_data.description",
                "unavailable_until_isolation_proof", "process_execution",
                new string[] { "process_execute" },
                new CommandInput[] {  },
                "[]",
                "[{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "dev_dump_data"));
            commands.Add(new CommandDefinition(
                "dev.dump_icons", "Dev",
                "Dev Dump Icons", "dev.dump_icons",
                CommandStatus.NotSupportedWithReason, "Run facman dev dump-icons --json", "execution_not_enabled",
                "command.dev.dump_icons.title", "command.dev.dump_icons.description",
                "unavailable_until_isolation_proof", "process_execution",
                new string[] { "process_execute" },
                new CommandInput[] {  },
                "[]",
                "[{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "dev_dump_icons"));
            commands.Add(new CommandDefinition(
                "dev.instrument_mod", "Dev",
                "Dev Instrument Mod", "dev.instrument_mod",
                CommandStatus.NotSupportedWithReason, "Run facman dev instrument-mod --json", "execution_not_enabled",
                "command.dev.instrument_mod.title", "command.dev.instrument_mod.description",
                "unavailable_until_isolation_proof", "process_execution",
                new string[] { "process_execute" },
                new CommandInput[] {  },
                "[]",
                "[{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "dev_instrument_mod"));
            commands.Add(new CommandDefinition(
                "diagnostics.export", "Diagnostics",
                "Diagnostics Export", "diagnostics.export",
                CommandStatus.Implemented, "Run facman diagnostics export --instance <instance-id> --out <bundle.zip> --json", "",
                "command.diagnostics.export.title", "command.diagnostics.export.description",
                "available", "persistent_local_write",
                new string[] { "workspace_read", "workspace_write" },
                new CommandInput[] { new CommandInput("instance_id", "Instance ID", true, "identifier", false, "instance_id", null), new CommandInput("output_path", "Output Path", true, "path", false, "output_path", null) },
                "[]",
                "[{\"name\":\"--instance\",\"value\":\"instance-id\",\"repeatable\":false},{\"name\":\"--out\",\"value\":\"bundle.zip\",\"repeatable\":false},{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "diagnostics_export"));
            commands.Add(new CommandDefinition(
                "diagnostics.redact", "Diagnostics",
                "Diagnostics Redact", "diagnostics.redact",
                CommandStatus.Implemented, "Run facman diagnostics redact <path> --json", "",
                "command.diagnostics.redact.title", "command.diagnostics.redact.description",
                "available", "read_only",
                new string[] { "workspace_read" },
                new CommandInput[] { new CommandInput("path", "Path", true, "path", false, "path", null) },
                "[{\"name\":\"path\",\"required\":true}]",
                "[{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "diagnostics_redact"));
            commands.Add(new CommandDefinition(
                "doctor.explain", "Doctor",
                "Doctor Explain", "doctor.explain",
                CommandStatus.Implemented, "Run facman doctor explain --json", "",
                "command.doctor.explain.title", "command.doctor.explain.description",
                "available", "read_only",
                new string[] { "workspace_read" },
                new CommandInput[] {  },
                "[]",
                "[{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "doctor_explain"));
            commands.Add(new CommandDefinition(
                "doctor.run", "Doctor",
                "Doctor Run", "doctor.run",
                CommandStatus.Implemented, "Run facman doctor --json", "",
                "command.doctor.run.title", "command.doctor.run.description",
                "available", "read_only",
                new string[] { "workspace_read" },
                new CommandInput[] { new CommandInput("roots", "Roots", false, "string_array", true, "roots", null) },
                "[]",
                "[{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "doctor_run"));
            commands.Add(new CommandDefinition(
                "factorio.product.inspect", "Factorio",
                "Factorio Product Inspect", "factorio.product.inspect",
                CommandStatus.Implemented, "Run FLB command bridge: factorio.product.inspect", "",
                "command.factorio.product.inspect.title", "command.factorio.product.inspect.description",
                "available", "read_only",
                new string[] { "none" },
                new CommandInput[] {  },
                "[]",
                "[]",
                "product_inspect"));
            commands.Add(new CommandDefinition(
                "install_refs.list", "Install Refs",
                "Install Refs List", "install_refs.list",
                CommandStatus.Implemented, "Run facman installs list --json", "",
                "command.install_refs.list.title", "command.install_refs.list.description",
                "available", "read_only",
                new string[] { "workspace_read" },
                new CommandInput[] {  },
                "[]",
                "[{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "install_list"));
            commands.Add(new CommandDefinition(
                "installs.import", "Install Refs",
                "Installs Import", "install_refs.import",
                CommandStatus.Implemented, "Run facman installs import <factorio-dir> --id <install-id> --json", "",
                "command.install_refs.import.title", "command.install_refs.import.description",
                "available", "persistent_local_write",
                new string[] { "workspace_read", "workspace_write" },
                new CommandInput[] { new CommandInput("path", "Path", true, "path", false, "path", null), new CommandInput("install_id", "Install ID", true, "identifier", false, "install_id", null) },
                "[{\"name\":\"factorio-dir\",\"required\":true}]",
                "[{\"name\":\"--id\",\"value\":\"install-id\",\"repeatable\":false},{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "install_import"));
            commands.Add(new CommandDefinition(
                "installs.inspect", "Install Refs",
                "Installs Inspect", "install_refs.inspect",
                CommandStatus.Implemented, "Run facman installs inspect <install-id> --json", "",
                "command.install_refs.inspect.title", "command.install_refs.inspect.description",
                "available", "read_only",
                new string[] { "workspace_read" },
                new CommandInput[] { new CommandInput("install_id", "Install ID", true, "identifier", false, "install_id", null) },
                "[{\"name\":\"install-id\",\"required\":true}]",
                "[{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "install_inspect"));
            commands.Add(new CommandDefinition(
                "installs.install_version", "Installs",
                "Installs Install Version", "installs.install_version",
                CommandStatus.NotSupportedWithReason, "Run facman installs install-version <version> --archive <path> --json", "setup_plan_inputs_not_confirmed",
                "command.installs.install_version.title", "command.installs.install_version.description",
                "unavailable_until_gateway", "read_only",
                new string[] { "setup_preview" },
                new CommandInput[] { new CommandInput("version", "Version", true, "string", false, "version", null), new CommandInput("archive", "Archive", false, "path", false, "archive", null) },
                "[{\"name\":\"version\",\"required\":true}]",
                "[{\"name\":\"--archive\",\"value\":\"path\",\"repeatable\":false},{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "installs_install_version"));
            commands.Add(new CommandDefinition(
                "installs.repair", "Installs",
                "Installs Repair", "installs.repair",
                CommandStatus.NotSupportedWithReason, "Run facman installs repair <install-id> --json", "ownership_denied",
                "command.installs.repair.title", "command.installs.repair.description",
                "unavailable_until_gateway", "read_only",
                new string[] { "setup_preview", "foreign_owned_refusal" },
                new CommandInput[] { new CommandInput("id", "ID", true, "identifier", false, "id", null) },
                "[{\"name\":\"install-id\",\"required\":true}]",
                "[{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "installs_repair"));
            commands.Add(new CommandDefinition(
                "installs.scan", "Install Refs",
                "Installs Scan", "install_refs.scan",
                CommandStatus.Implemented, "Run facman installs scan --json", "",
                "command.install_refs.scan.title", "command.install_refs.scan.description",
                "available", "read_only",
                new string[] { "workspace_read" },
                new CommandInput[] { new CommandInput("roots", "Roots", false, "string_array", true, "roots", null) },
                "[]",
                "[{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "install_scan"));
            commands.Add(new CommandDefinition(
                "installs.uninstall", "Installs",
                "Installs Uninstall", "installs.uninstall",
                CommandStatus.NotSupportedWithReason, "Run facman installs uninstall <install-id> --json", "ownership_denied",
                "command.installs.uninstall.title", "command.installs.uninstall.description",
                "unavailable_until_gateway", "read_only",
                new string[] { "setup_preview", "foreign_owned_refusal" },
                new CommandInput[] { new CommandInput("id", "ID", true, "identifier", false, "id", null) },
                "[{\"name\":\"install-id\",\"required\":true}]",
                "[{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "installs_uninstall"));
            commands.Add(new CommandDefinition(
                "installs.verify", "Installs",
                "Installs Verify", "installs.verify",
                CommandStatus.NotSupportedWithReason, "Run facman installs verify <install-id> --json", "setup_verification_not_implemented",
                "command.installs.verify.title", "command.installs.verify.description",
                "unavailable_until_gateway", "read_only",
                new string[] { "setup_preview" },
                new CommandInput[] { new CommandInput("id", "ID", true, "identifier", false, "id", null) },
                "[{\"name\":\"install-id\",\"required\":true}]",
                "[{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "installs_verify"));
            commands.Add(new CommandDefinition(
                "instance.export", "Instance",
                "Instance Export", "instance.export",
                CommandStatus.Implemented, "Run facman export instance <instance-id> <pack.zip> --json", "",
                "command.instance.export.title", "command.instance.export.description",
                "available", "persistent_local_write",
                new string[] { "workspace_read", "workspace_write" },
                new CommandInput[] { new CommandInput("instance_id", "Instance ID", true, "identifier", false, "instance_id", null), new CommandInput("output_path", "Output Path", true, "path", false, "output_path", null) },
                "[{\"name\":\"instance-id\",\"required\":true},{\"name\":\"pack.zip\",\"required\":true}]",
                "[{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "instance_export"));
            commands.Add(new CommandDefinition(
                "instance.import", "Instance",
                "Instance Import", "instance.import",
                CommandStatus.Implemented, "Run facman import instance <pack.zip> --json", "",
                "command.instance.import.title", "command.instance.import.description",
                "available", "persistent_local_write",
                new string[] { "workspace_read", "workspace_write" },
                new CommandInput[] { new CommandInput("source_path", "Source Path", true, "path", false, "source_path", null), new CommandInput("instance_id", "Instance ID", false, "identifier", false, "instance_id", null) },
                "[{\"name\":\"pack.zip\",\"required\":true}]",
                "[{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "instance_import"));
            commands.Add(new CommandDefinition(
                "instance.list", "Instance",
                "Instance List", "instance.list",
                CommandStatus.Implemented, "Run facman instances list --json", "",
                "command.instance.list.title", "command.instance.list.description",
                "available", "read_only",
                new string[] { "workspace_read" },
                new CommandInput[] {  },
                "[]",
                "[{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "instance_list"));
            commands.Add(new CommandDefinition(
                "instances.create", "Instance",
                "Instances Create", "instance.create",
                CommandStatus.Implemented, "Run facman instances create <name> --install <install-id> --json", "",
                "command.instance.create.title", "command.instance.create.description",
                "available", "persistent_local_write",
                new string[] { "workspace_read", "workspace_write" },
                new CommandInput[] { new CommandInput("display_name", "Display Name", true, "string", false, "display_name", null), new CommandInput("instance_id", "Instance ID", true, "identifier", false, "instance_id", null), new CommandInput("install_id", "Install ID", true, "identifier", false, "install_id", null), new CommandInput("template_id", "Template ID", false, "identifier", false, "template_id", null) },
                "[{\"name\":\"name\",\"required\":true}]",
                "[{\"name\":\"--install\",\"value\":\"install-id\",\"repeatable\":false},{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "instance_create"));
            commands.Add(new CommandDefinition(
                "launch.plan", "Launch Plan",
                "Launch Plan", "launch_plan.build",
                CommandStatus.Implemented, "Run facman launch plan <instance-id> --json", "",
                "command.launch_plan.build.title", "command.launch_plan.build.description",
                "available", "read_only",
                new string[] { "workspace_read" },
                new CommandInput[] { new CommandInput("instance_id", "Instance ID", true, "identifier", false, "instance_id", null) },
                "[{\"name\":\"instance-id\",\"required\":true}]",
                "[{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "launch_plan_build"));
            commands.Add(new CommandDefinition(
                "launch_plan.explain", "Launch Plan",
                "Launch Plan Explain", "launch_plan.explain",
                CommandStatus.Implemented, "Run facman launch explain <instance-id> --json", "",
                "command.launch_plan.explain.title", "command.launch_plan.explain.description",
                "available", "read_only",
                new string[] { "workspace_read" },
                new CommandInput[] { new CommandInput("instance_id", "Instance ID", true, "identifier", false, "instance_id", null) },
                "[{\"name\":\"instance-id\",\"required\":true}]",
                "[{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "launch_plan_explain"));
            commands.Add(new CommandDefinition(
                "launch_plan.preflight", "Launch Plan",
                "Launch Plan Preflight", "launch_plan.preflight",
                CommandStatus.Implemented, "Run facman launch plan <instance-id> --preflight --json", "",
                "command.launch_plan.preflight.title", "command.launch_plan.preflight.description",
                "available", "read_only",
                new string[] { "workspace_read" },
                new CommandInput[] { new CommandInput("instance_id", "Instance ID", true, "identifier", false, "instance_id", null) },
                "[{\"name\":\"instance-id\",\"required\":true}]",
                "[{\"name\":\"--preflight\",\"value\":null,\"repeatable\":false},{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "launch_plan_preflight"));
            commands.Add(new CommandDefinition(
                "mods.import", "Mods",
                "Mods Import", "mods.import",
                CommandStatus.Implemented, "Run facman mods import <mod.zip> --instance <instance-id> --json", "",
                "command.mods.import.title", "command.mods.import.description",
                "available", "persistent_local_write",
                new string[] { "workspace_read", "workspace_write" },
                new CommandInput[] { new CommandInput("source_path", "Source Path", true, "path", false, "source_path", null), new CommandInput("instance_id", "Instance ID", true, "identifier", false, "instance_id", null) },
                "[{\"name\":\"mod.zip\",\"required\":true}]",
                "[{\"name\":\"--instance\",\"value\":\"instance-id\",\"repeatable\":false},{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "mods_import"));
            commands.Add(new CommandDefinition(
                "mods.install", "Mods",
                "Mods Install", "mods.install",
                CommandStatus.NotSupportedWithReason, "Run facman mods install <name> --instance <id> --json", "network_forbidden",
                "command.mods.install.title", "command.mods.install.description",
                "unavailable_until_gateway", "read_only",
                new string[] { "network_read" },
                new CommandInput[] { new CommandInput("query", "Query", false, "string", false, "query", null), new CommandInput("instance_id", "Instance ID", false, "identifier", false, "instance_id", null) },
                "[{\"name\":\"name\",\"required\":true}]",
                "[{\"name\":\"--instance\",\"value\":\"id\",\"repeatable\":false},{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "mods_install"));
            commands.Add(new CommandDefinition(
                "mods.search", "Mods",
                "Mods Search", "mods.search",
                CommandStatus.NotSupportedWithReason, "Run facman mods search <query> --json", "network_forbidden",
                "command.mods.search.title", "command.mods.search.description",
                "unavailable_until_gateway", "read_only",
                new string[] { "network_read" },
                new CommandInput[] { new CommandInput("query", "Query", false, "string", false, "query", null) },
                "[{\"name\":\"query\",\"required\":true}]",
                "[{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "mods_search"));
            commands.Add(new CommandDefinition(
                "mods.update", "Mods",
                "Mods Update", "mods.update",
                CommandStatus.NotSupportedWithReason, "Run facman mods update --instance <id> --json", "network_forbidden",
                "command.mods.update.title", "command.mods.update.description",
                "unavailable_until_gateway", "read_only",
                new string[] { "network_read" },
                new CommandInput[] { new CommandInput("instance_id", "Instance ID", false, "identifier", false, "instance_id", null) },
                "[]",
                "[{\"name\":\"--instance\",\"value\":\"id\",\"repeatable\":false},{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "mods_update"));
            commands.Add(new CommandDefinition(
                "modsets.explain", "Modsets",
                "Modsets Explain", "modsets.explain",
                CommandStatus.Implemented, "Run facman modsets explain <instance-id> --json", "",
                "command.modsets.explain.title", "command.modsets.explain.description",
                "available", "read_only",
                new string[] { "workspace_read" },
                new CommandInput[] { new CommandInput("instance_id", "Instance ID", true, "identifier", false, "instance_id", null) },
                "[{\"name\":\"instance-id\",\"required\":true}]",
                "[{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "modsets_explain"));
            commands.Add(new CommandDefinition(
                "modsets.export", "Modsets",
                "Modsets Export", "modsets.export",
                CommandStatus.Implemented, "Run facman modsets export <instance-id> <pack.zip> --json", "",
                "command.modsets.export.title", "command.modsets.export.description",
                "available", "persistent_local_write",
                new string[] { "workspace_read", "workspace_write" },
                new CommandInput[] { new CommandInput("instance_id", "Instance ID", true, "identifier", false, "instance_id", null), new CommandInput("output_path", "Output Path", true, "path", false, "output_path", null) },
                "[{\"name\":\"instance-id\",\"required\":true},{\"name\":\"pack.zip\",\"required\":true}]",
                "[{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "modsets_export"));
            commands.Add(new CommandDefinition(
                "modsets.lock", "Modsets",
                "Modsets Lock", "modsets.lock",
                CommandStatus.Implemented, "Run facman modsets lock <instance-id> --json", "",
                "command.modsets.lock.title", "command.modsets.lock.description",
                "available", "persistent_local_write",
                new string[] { "workspace_read", "workspace_write" },
                new CommandInput[] { new CommandInput("instance_id", "Instance ID", true, "identifier", false, "instance_id", null) },
                "[{\"name\":\"instance-id\",\"required\":true}]",
                "[{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "modsets_lock"));
            commands.Add(new CommandDefinition(
                "modsets.verify", "Modsets",
                "Modsets Verify", "modsets.verify",
                CommandStatus.Implemented, "Run facman modsets verify <instance-id> --json", "",
                "command.modsets.verify.title", "command.modsets.verify.description",
                "available", "read_only",
                new string[] { "workspace_read" },
                new CommandInput[] { new CommandInput("instance_id", "Instance ID", true, "identifier", false, "instance_id", null) },
                "[{\"name\":\"instance-id\",\"required\":true}]",
                "[{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "modsets_verify"));
            commands.Add(new CommandDefinition(
                "onboarding.plan", "Onboarding",
                "Onboarding Plan", "onboarding.plan",
                CommandStatus.Implemented, "Run facman onboarding plan --preferred-install <install-id> --name <display-name> --template <template-id> --json", "",
                "command.onboarding.plan.title", "command.onboarding.plan.description",
                "available", "read_only",
                new string[] { "workspace_read" },
                new CommandInput[] { new CommandInput("preferred_install", "Preferred Install", false, "identifier", false, "preferred_install", null), new CommandInput("instance_display_name", "Instance Display Name", false, "string", false, "instance_display_name", null), new CommandInput("template_id", "Template ID", false, "identifier", false, "template_id", null), new CommandInput("workspace", "Workspace", false, "path", false, "workspace", null) },
                "[]",
                "[{\"name\":\"--preferred-install\",\"value\":\"install-id\",\"repeatable\":false},{\"name\":\"--name\",\"value\":\"display-name\",\"repeatable\":false},{\"name\":\"--template\",\"value\":\"template-id\",\"repeatable\":false},{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "onboarding_plan"));
            commands.Add(new CommandDefinition(
                "package.verify", "Package",
                "Package Verify", "package.verify",
                CommandStatus.NotSupportedWithReason, "Run facman package verify --json", "setup_unavailable",
                "command.package.verify.title", "command.package.verify.description",
                "unavailable_until_gateway", "read_only",
                new string[] { "setup_preview" },
                new CommandInput[] { new CommandInput("path", "Path", false, "path", false, "path", null) },
                "[]",
                "[{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "package_verify"));
            commands.Add(new CommandDefinition(
                "product.inspect", "Product",
                "Product Inspect", "product.inspect",
                CommandStatus.Implemented, "Run facman product inspect --json", "",
                "command.product.inspect.title", "command.product.inspect.description",
                "available", "read_only",
                new string[] { "none" },
                new CommandInput[] {  },
                "[]",
                "[{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "product_inspect"));
            commands.Add(new CommandDefinition(
                "run.execute", "Run",
                "Run Execute", "run.execute",
                CommandStatus.NotSupportedWithReason, "Run facman run <instance-id> --execute --json", "isolation_not_proven",
                "command.run.execute.title", "command.run.execute.description",
                "unavailable_until_isolation_proof", "read_only",
                new string[] { "workspace_read" },
                new CommandInput[] { new CommandInput("instance_id", "Instance ID", false, "identifier", false, "instance_id", null) },
                "[{\"name\":\"instance-id\",\"required\":true}]",
                "[{\"name\":\"--execute\",\"value\":null,\"repeatable\":false},{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "run_execute"));
            commands.Add(new CommandDefinition(
                "run.preview", "Run",
                "Run Preview", "run.preview",
                CommandStatus.Implemented, "Run facman run <instance-id> --json", "",
                "command.run.preview.title", "command.run.preview.description",
                "available", "read_only",
                new string[] { "workspace_read" },
                new CommandInput[] { new CommandInput("instance_id", "Instance ID", true, "identifier", false, "instance_id", null) },
                "[{\"name\":\"instance-id\",\"required\":true}]",
                "[{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "run_preview"));
            commands.Add(new CommandDefinition(
                "saves.backup", "Saves",
                "Saves Backup", "saves.backup",
                CommandStatus.Implemented, "Run facman saves backup <save> --instance <instance-id> --json", "",
                "command.saves.backup.title", "command.saves.backup.description",
                "available", "persistent_local_write",
                new string[] { "workspace_read", "workspace_write" },
                new CommandInput[] { new CommandInput("instance_id", "Instance ID", true, "identifier", false, "instance_id", null), new CommandInput("save", "Save", true, "string", false, "save", null), new CommandInput("output_path", "Output Path", false, "path", false, "output_path", null) },
                "[{\"name\":\"save\",\"required\":true}]",
                "[{\"name\":\"--instance\",\"value\":\"instance-id\",\"repeatable\":false},{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "saves_backup"));
            commands.Add(new CommandDefinition(
                "saves.clone", "Saves",
                "Saves Clone", "saves.clone",
                CommandStatus.Implemented, "Run facman saves clone <save> --instance <source-id> --to-instance <target-id> --json", "",
                "command.saves.clone.title", "command.saves.clone.description",
                "available", "persistent_local_write",
                new string[] { "workspace_read", "workspace_write" },
                new CommandInput[] { new CommandInput("source_instance_id", "Source Instance ID", true, "identifier", false, "source_instance_id", null), new CommandInput("target_instance_id", "Target Instance ID", true, "identifier", false, "target_instance_id", null), new CommandInput("save", "Save", true, "string", false, "save", null) },
                "[{\"name\":\"save\",\"required\":true}]",
                "[{\"name\":\"--instance\",\"value\":\"source-id\",\"repeatable\":false},{\"name\":\"--to-instance\",\"value\":\"target-id\",\"repeatable\":false},{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "saves_clone"));
            commands.Add(new CommandDefinition(
                "saves.list", "Saves",
                "Saves List", "saves.list",
                CommandStatus.Implemented, "Run facman saves list --instance <instance-id> --json", "",
                "command.saves.list.title", "command.saves.list.description",
                "available", "read_only",
                new string[] { "workspace_read" },
                new CommandInput[] { new CommandInput("instance_id", "Instance ID", true, "identifier", false, "instance_id", null) },
                "[]",
                "[{\"name\":\"--instance\",\"value\":\"instance-id\",\"repeatable\":false},{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "saves_list"));
            commands.Add(new CommandDefinition(
                "servers.create", "Servers",
                "Servers Create", "servers.create",
                CommandStatus.Implemented, "Run facman servers create <name> --instance <id> --json", "",
                "command.servers.create.title", "command.servers.create.description",
                "available", "persistent_local_write",
                new string[] { "workspace_read", "workspace_write" },
                new CommandInput[] { new CommandInput("name", "Name", true, "string", false, "name", null), new CommandInput("id", "ID", false, "identifier", false, "id", null), new CommandInput("instance_id", "Instance ID", true, "identifier", false, "instance_id", null) },
                "[{\"name\":\"name\",\"required\":true}]",
                "[{\"name\":\"--instance\",\"value\":\"id\",\"repeatable\":false},{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "servers_create"));
            commands.Add(new CommandDefinition(
                "servers.list", "Servers",
                "Servers List", "servers.list",
                CommandStatus.Implemented, "Run facman servers list --json", "",
                "command.servers.list.title", "command.servers.list.description",
                "available", "read_only",
                new string[] { "workspace_read" },
                new CommandInput[] {  },
                "[]",
                "[{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "servers_list"));
            commands.Add(new CommandDefinition(
                "servers.rcon", "Servers",
                "Servers RCON", "servers.rcon",
                CommandStatus.NotSupportedWithReason, "Run facman servers rcon <server-id> --json", "execution_not_enabled",
                "command.servers.rcon.title", "command.servers.rcon.description",
                "unavailable_until_isolation_proof", "process_execution",
                new string[] { "workspace_read", "process_execute" },
                new CommandInput[] { new CommandInput("id", "ID", true, "identifier", false, "id", null) },
                "[{\"name\":\"server-id\",\"required\":true}]",
                "[{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "servers_rcon"));
            commands.Add(new CommandDefinition(
                "servers.start", "Servers",
                "Servers Start", "servers.start",
                CommandStatus.NotSupportedWithReason, "Run facman servers start <server-id> --json", "execution_not_enabled",
                "command.servers.start.title", "command.servers.start.description",
                "unavailable_until_isolation_proof", "process_execution",
                new string[] { "workspace_read", "process_execute" },
                new CommandInput[] { new CommandInput("id", "ID", true, "identifier", false, "id", null) },
                "[{\"name\":\"server-id\",\"required\":true}]",
                "[{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "servers_start"));
            commands.Add(new CommandDefinition(
                "servers.stop", "Servers",
                "Servers Stop", "servers.stop",
                CommandStatus.NotSupportedWithReason, "Run facman servers stop <server-id> --json", "execution_not_enabled",
                "command.servers.stop.title", "command.servers.stop.description",
                "unavailable_until_isolation_proof", "process_execution",
                new string[] { "workspace_read", "process_execute" },
                new CommandInput[] { new CommandInput("id", "ID", true, "identifier", false, "id", null) },
                "[{\"name\":\"server-id\",\"required\":true}]",
                "[{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "servers_stop"));
            commands.Add(new CommandDefinition(
                "setup.preview", "Setup",
                "Setup Preview", "setup.preview",
                CommandStatus.NotSupportedWithReason, "Run facman setup preview --json", "setup_unavailable",
                "command.setup.preview.title", "command.setup.preview.description",
                "unavailable_until_gateway", "read_only",
                new string[] { "workspace_read" },
                new CommandInput[] {  },
                "[]",
                "[{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "setup_preview"));
            commands.Add(new CommandDefinition(
                "workspace.migration.apply", "Workspace",
                "Workspace Migration Apply", "workspace.migration.apply",
                CommandStatus.Implemented, "Run facman workspace migration apply --json", "",
                "command.workspace.migration.apply.title", "command.workspace.migration.apply.description",
                "available", "persistent_local_write",
                new string[] { "workspace_read", "workspace_write" },
                new CommandInput[] {  },
                "[]",
                "[{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "migration_apply"));
            commands.Add(new CommandDefinition(
                "workspace.migration.inspect", "Workspace",
                "Workspace Migration Inspect", "workspace.migration.inspect",
                CommandStatus.Implemented, "Run facman workspace migration inspect --json", "",
                "command.workspace.migration.inspect.title", "command.workspace.migration.inspect.description",
                "available", "read_only",
                new string[] { "workspace_read" },
                new CommandInput[] {  },
                "[]",
                "[{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "migration_inspect"));
            commands.Add(new CommandDefinition(
                "workspace.migration.plan", "Workspace",
                "Workspace Migration Plan", "workspace.migration.plan",
                CommandStatus.Implemented, "Run facman workspace migration plan --json", "",
                "command.workspace.migration.plan.title", "command.workspace.migration.plan.description",
                "available", "read_only",
                new string[] { "workspace_read" },
                new CommandInput[] {  },
                "[]",
                "[{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "migration_plan"));
            commands.Add(new CommandDefinition(
                "workspace.paths", "Workspace",
                "Workspace Paths", "workspace.paths",
                CommandStatus.Implemented, "Run facman workspace paths --json", "",
                "command.workspace.paths.title", "command.workspace.paths.description",
                "available", "read_only",
                new string[] { "workspace_read" },
                new CommandInput[] {  },
                "[]",
                "[{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "workspace_paths"));
            commands.Add(new CommandDefinition(
                "workspace.recovery.apply", "Workspace",
                "Workspace Recovery Apply", "workspace.recovery.apply",
                CommandStatus.Implemented, "Run facman workspace recovery apply <transaction-id> --json", "",
                "command.workspace.recovery.apply.title", "command.workspace.recovery.apply.description",
                "available", "persistent_local_write",
                new string[] { "workspace_read", "workspace_write" },
                new CommandInput[] { new CommandInput("transaction_id", "Transaction ID", true, "identifier", false, "transaction_id", null) },
                "[{\"name\":\"transaction-id\",\"required\":true}]",
                "[{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "recovery_apply"));
            commands.Add(new CommandDefinition(
                "workspace.recovery.inspect", "Workspace",
                "Workspace Recovery Inspect", "workspace.recovery.inspect",
                CommandStatus.Implemented, "Run facman workspace recovery inspect --json", "",
                "command.workspace.recovery.inspect.title", "command.workspace.recovery.inspect.description",
                "available", "read_only",
                new string[] { "workspace_read" },
                new CommandInput[] {  },
                "[]",
                "[{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "recovery_inspect"));
            commands.Add(new CommandDefinition(
                "workspace.recovery.plan", "Workspace",
                "Workspace Recovery Plan", "workspace.recovery.plan",
                CommandStatus.Implemented, "Run facman workspace recovery plan <transaction-id> --json", "",
                "command.workspace.recovery.plan.title", "command.workspace.recovery.plan.description",
                "available", "read_only",
                new string[] { "workspace_read" },
                new CommandInput[] { new CommandInput("transaction_id", "Transaction ID", true, "identifier", false, "transaction_id", null) },
                "[{\"name\":\"transaction-id\",\"required\":true}]",
                "[{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "recovery_plan"));
            commands.Add(new CommandDefinition(
                "workspace.status", "Workspace",
                "Workspace Status", "workspace.status",
                CommandStatus.Implemented, "Run facman workspace status --json", "",
                "command.workspace.status.title", "command.workspace.status.description",
                "available", "read_only",
                new string[] { "workspace_read" },
                new CommandInput[] {  },
                "[]",
                "[{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "workspace_status"));
            return commands.AsReadOnly();
        }
    }
}
