// Generated by tools/codegen/generate_metadata.py; do not edit.
// release/index/version.v2.toml sha256: a28d257b66033514e7621e9c9818ac545e0ecddc638544fe4b32d60e1b536e1d
// SPDX-FileCopyrightText: 2026 Jules C
// SPDX-License-Identifier: MIT

using System.Reflection;

[assembly: AssemblyTitle("FacMan")]
[assembly: AssemblyProduct("FacMan")]
[assembly: AssemblyVersion("0.1.0.0")]
[assembly: AssemblyFileVersion("0.1.0.0")]
[assembly: AssemblyInformationalVersion("0.1.0-alpha.5")]

namespace FacMan.WinForms
{
    internal static class GeneratedProductMetadata
    {
        internal const string Product = "FacMan";
        internal const string ProductId = "facman";
        internal const string SemanticVersion = "0.1.0-alpha.5";
        internal const string CanonicalVersion = "facman-0.1.0-alpha.5";
        internal const string FileVersion = "0.1.0.0";
        internal const string AboutLead = "FacMan 0.1.0-alpha.5 C1 reference shell";
    }
}
