// SPDX-FileCopyrightText: 2026 Jules C
// SPDX-License-Identifier: MIT
// Generated by tools/codegen/generate_contracts.py; do not edit.
using System.Collections.Generic;

namespace FacMan.WinForms.GeneratedContracts
{
    public static class PresentationContractIdentity
    {
        public const string SourceDigest = "2d54c930227c7f7c6854493a739bd83ac58bd73f0715d12f6b0c7bc18f7147c1";
    }

    public sealed class SemanticActionRequest
    {
        public string ActionId { get; set; }
        public string ExpectedSnapshotRevision { get; set; }
        public string RequestId { get; set; }
        public string Scope { get; set; }
        public string AttemptId { get; set; }
        public string Confirmation { get; set; }
        public string DisplayName { get; set; }
        public string DurableOperationId { get; set; }
        public string IdempotencyKey { get; set; }
        public string InstallationId { get; set; }
        public string InstallationPath { get; set; }
        public string ModIdentity { get; set; }
        public string NewInstanceId { get; set; }
        public string OutputPath { get; set; }
        public string ProfileId { get; set; }
        public IList<string> Roots { get; set; }
        public string Save { get; set; }
        public string SelectedInstanceId { get; set; }
        public string SourceDataRoot { get; set; }
        public string TemplateId { get; set; }
        public string TransactionId { get; set; }
    }

    public sealed class PresentationQuery
    {
        public string Scope { get; set; }
        public string KnownRevision { get; set; }
        public string Search { get; set; }
        public string SelectedInstanceId { get; set; }
    }

    public sealed class PresentationSnapshot
    {
        public IDictionary<string, object> ActiveOperations { get; set; }
        public IDictionary<string, object> AvailableSemanticActions { get; set; }
        public IDictionary<string, object> BackendProviderIdentity { get; set; }
        public IDictionary<string, object> Command { get; set; }
        public IDictionary<string, object> DependencyIdentities { get; set; }
        public IDictionary<string, object> Freshness { get; set; }
        public IDictionary<string, object> LastRun { get; set; }
        public IDictionary<string, object> PackageIdentity { get; set; }
        public IDictionary<string, object> Page { get; set; }
        public IDictionary<string, object> Readiness { get; set; }
        public IDictionary<string, object> Recovery { get; set; }
        public string Revision { get; set; }
        public IDictionary<string, object> Schema { get; set; }
        public IDictionary<string, object> SelectedContext { get; set; }
        public string SnapshotId { get; set; }
        public IDictionary<string, object> SpecificBlockers { get; set; }
        public IDictionary<string, object> SupportClassification { get; set; }
        public IDictionary<string, object> WorkspaceHealth { get; set; }
    }

    public sealed class SemanticActionResult
    {
        public string ActionId { get; set; }
        public IDictionary<string, object> ActionPayload { get; set; }
        public IDictionary<string, object> Command { get; set; }
        public IList<IDictionary<string, object>> Diagnostics { get; set; }
        public IList<IDictionary<string, object>> Effects { get; set; }
        public IDictionary<string, object> Invalidation { get; set; }
        public IDictionary<string, object> Operation { get; set; }
        public IDictionary<string, object> Outcome { get; set; }
        public IDictionary<string, object> Problems { get; set; }
        public IDictionary<string, object> ReplacementSnapshot { get; set; }
        public string RequestId { get; set; }
        public IDictionary<string, object> Schema { get; set; }
    }
}
