// Generated by tools/codegen/generate_metadata.py; do not edit.
// release/index/version.v2.toml sha256: c6f616bf103dde3a75251294eaefde33f6bb0950f1fb247d0b1bd9487369580c
// SPDX-FileCopyrightText: 2026 Jules C
// SPDX-License-Identifier: MIT

using System.Reflection;

[assembly: AssemblyTitle("FacMan")]
[assembly: AssemblyProduct("FacMan")]
[assembly: AssemblyVersion("0.1.0.0")]
[assembly: AssemblyFileVersion("0.1.0.0")]
[assembly: AssemblyInformationalVersion("0.1.0-alpha.6")]

namespace FacMan.WinForms
{
    internal static class GeneratedProductMetadata
    {
        internal const string Product = "FacMan";
        internal const string ProductId = "facman";
        internal const string SemanticVersion = "0.1.0-alpha.6";
        internal const string CanonicalVersion = "facman-0.1.0-alpha.6";
        internal const string FileVersion = "0.1.0.0";
        internal const string AboutLead = "FacMan 0.1.0-alpha.6 C1 reference shell";
    }
}
