// SPDX-FileCopyrightText: 2026 Jules C
// SPDX-License-Identifier: MIT
// Generated by tools/codegen/generate_contracts.py; do not edit.
using System.Collections.Generic;

namespace FacMan.WinForms.GeneratedContracts
{
    public static class PresentationContractIdentity
    {
        public const string SourceDigest = "29d937beb4b0f6a61a2d74c4aa1c0e2f22eb1304c6d72630486e7514ee120200";
    }

    public sealed class SemanticActionRequest
    {
        public string ActionId { get; set; }
        public string ExpectedSnapshotRevision { get; set; }
        public string RequestId { get; set; }
        public string Scope { get; set; }
        public string AttemptId { get; set; }
        public string Confirmation { get; set; }
        public string DisplayName { get; set; }
        public string DurableOperationId { get; set; }
        public string IdempotencyKey { get; set; }
        public string InstallationId { get; set; }
        public string InstallationPath { get; set; }
        public string ModIdentity { get; set; }
        public string NewInstanceId { get; set; }
        public string OutputPath { get; set; }
        public string ProfileId { get; set; }
        public IList<string> Roots { get; set; }
        public string Save { get; set; }
        public string SelectedInstanceId { get; set; }
        public string SourceDataRoot { get; set; }
        public string TemplateId { get; set; }
        public string TransactionId { get; set; }
    }

    public sealed class PresentationQuery
    {
        public string Scope { get; set; }
        public string KnownRevision { get; set; }
        public string Search { get; set; }
        public string SelectedInstanceId { get; set; }
    }

    public sealed class FrontendCancellationRequest
    {
        public string AttemptId { get; set; }
        public string Confirmation { get; set; }
        public long DeadlineMs { get; set; }
        public bool DryRun { get; set; }
        public string ExpectedSnapshotRevision { get; set; }
        public bool Explain { get; set; }
        public string IdempotencyKey { get; set; }
        public string OperationId { get; set; }
        public string RequestId { get; set; }
        public string TargetInstanceId { get; set; }
        public string TargetOperationId { get; set; }
    }

    public sealed class FrontendCapabilitySnapshot
    {
        public IDictionary<string, object> BackendIdentity { get; set; }
        public string CommandCatalogSha256 { get; set; }
        public string ContractSetSha256 { get; set; }
        public string PresentationSchema { get; set; }
        public string Schema { get; set; }
        public string SemanticActionSchema { get; set; }
        public string Transport { get; set; }
        public IList<long> TransportProtocolVersions { get; set; }
        public IList<string> TypedMethods { get; set; }
        public string RawCanonicalJson { get; set; }
    }

    public sealed class FrontendExecutionCorrelation
    {
        public string AttemptId { get; set; }
        public string OperationId { get; set; }
        public string OperationOutcome { get; set; }
        public string Outcome { get; set; }
        public bool Redacted { get; set; }
        public string RequestId { get; set; }
        public string Schema { get; set; }
    }

    public sealed class FrontendOperationInspectRequest
    {
        public string AttemptId { get; set; }
        public long DeadlineMs { get; set; }
        public string OperationId { get; set; }
        public string RequestId { get; set; }
        public string TargetOperationId { get; set; }
        public string TargetInstanceId { get; set; }
    }

    public sealed class FrontendOperationProjection
    {
        public string AttemptId { get; set; }
        public string Authority { get; set; }
        public string Kind { get; set; }
        public string OperationId { get; set; }
        public IDictionary<string, object> RawProjection { get; set; }
        public string Schema { get; set; }
        public string SnapshotRevision { get; set; }
        public string State { get; set; }
        public string TargetInstanceId { get; set; }
        public string TerminalOutcome { get; set; }
        public string RawCanonicalJson { get; set; }
    }

    public sealed class FrontendRequestContext
    {
        public string AttemptId { get; set; }
        public long DeadlineMs { get; set; }
        public bool DryRun { get; set; }
        public bool Explain { get; set; }
        public string OperationId { get; set; }
        public string RequestId { get; set; }
    }

    public sealed class PresentationActionReceipt
    {
        public string ActionId { get; set; }
        public string AttemptId { get; set; }
        public string Authority { get; set; }
        public long ContractVersion { get; set; }
        public IList<string> EffectSet { get; set; }
        public string IdempotencyKey { get; set; }
        public string KeyDigest { get; set; }
        public string OperationId { get; set; }
        public string RequestFingerprint { get; set; }
        public string RequestId { get; set; }
        public string RequestJson { get; set; }
        public string ResultDigest { get; set; }
        public string ResultJson { get; set; }
        public long ResultLength { get; set; }
        public string Schema { get; set; }
        public string Scope { get; set; }
        public string State { get; set; }
        public string TargetInstallationId { get; set; }
        public string TargetInstanceId { get; set; }
    }

    public sealed class PresentationSnapshot
    {
        public IList<IDictionary<string, object>> ActiveOperations { get; set; }
        public IList<IDictionary<string, object>> AvailableSemanticActions { get; set; }
        public IDictionary<string, object> BackendProviderIdentity { get; set; }
        public string Command { get; set; }
        public IDictionary<string, object> DependencyIdentities { get; set; }
        public IDictionary<string, object> Freshness { get; set; }
        public IDictionary<string, object> LastRun { get; set; }
        public IDictionary<string, object> PackageIdentity { get; set; }
        public IDictionary<string, object> Page { get; set; }
        public IDictionary<string, object> Readiness { get; set; }
        public IDictionary<string, object> Recovery { get; set; }
        public string Revision { get; set; }
        public string Schema { get; set; }
        public IDictionary<string, object> SelectedContext { get; set; }
        public string SnapshotId { get; set; }
        public IList<IDictionary<string, object>> SpecificBlockers { get; set; }
        public string SupportClassification { get; set; }
        public IDictionary<string, object> WorkspaceHealth { get; set; }
        public string RawCanonicalJson { get; set; }
    }

    public sealed class SemanticActionResult
    {
        public string ActionId { get; set; }
        public IDictionary<string, object> ActionPayload { get; set; }
        public string Command { get; set; }
        public IList<string> Diagnostics { get; set; }
        public IList<string> Effects { get; set; }
        public IDictionary<string, object> Invalidation { get; set; }
        public IDictionary<string, object> Operation { get; set; }
        public string Outcome { get; set; }
        public IList<IDictionary<string, object>> Problems { get; set; }
        public IDictionary<string, object> ReplacementSnapshot { get; set; }
        public string RequestId { get; set; }
        public string Schema { get; set; }
        public string RawCanonicalJson { get; set; }
    }
}
