// Generated by tools/codegen/generate_metadata.py; source-sha256: f0fab302a8d39cec282d9110591af52422d5e548cf99ccc1e5a9e20f27917058.
// SPDX-FileCopyrightText: 2026 Jules C
// SPDX-License-Identifier: MIT

using System;
using System.Collections.Generic;

namespace FacMan.WinForms
{
    public static class GeneratedCommandCatalog
    {
        private static readonly IList<CommandDefinition> Commands = Build();

        public static IList<CommandDefinition> All() { return Commands; }

        public static CommandDefinition Find(string commandId)
        {
            foreach (CommandDefinition command in Commands)
                if (String.Equals(command.Id, commandId, StringComparison.Ordinal)) return command;
            throw new CommandValidationException("Unknown command id: " + commandId);
        }

        public static IDictionary<string, object> BuildPayload(CommandDefinition command, IDictionary<string, string> inputs)
        {
            Dictionary<string, object> payload = new Dictionary<string, object>();
            foreach (CommandInput input in command.Inputs)
            {
                string value;
                bool present = inputs.TryGetValue(input.Key, out value) && !String.IsNullOrWhiteSpace(value);
                if (input.Required && !present) throw new CommandValidationException("Missing required input: " + input.Key);
                if (!present) continue;
                value = value.Trim();
                if (input.Type == "string_array")
                {
                    List<string> values = new List<string>();
                    foreach (string part in value.Split(new char[] { '\r', '\n' }, StringSplitOptions.RemoveEmptyEntries))
                        if (!String.IsNullOrWhiteSpace(part)) values.Add(part.Trim());
                    payload[input.RequestField] = values;
                }
                else payload[input.RequestField] = value;
            }
            return payload;
        }

        private static IList<CommandDefinition> Build()
        {
            List<CommandDefinition> commands = new List<CommandDefinition>();
            commands.Add(new CommandDefinition(
                "capabilities.inspect", "Capabilities",
                "Capabilities Inspect", "capabilities.inspect",
                CommandStatus.Implemented, "Run facman capabilities inspect --json", "",
                "command.capabilities.inspect.title", "command.capabilities.inspect.description",
                "available", "read_only",
                true,
                new string[] { "workspace_read" },
                new CommandInput[] {  },
                "[]",
                "[{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "capabilities_inspect"));
            commands.Add(new CommandDefinition(
                "dev.benchmark", "Dev",
                "Dev Benchmark", "dev.benchmark",
                CommandStatus.NotSupportedWithReason, "Run facman dev benchmark --json", "execution_not_enabled",
                "command.dev.benchmark.title", "command.dev.benchmark.description",
                "unavailable_until_isolation_proof", "process_execution",
                false,
                new string[] { "process_execute" },
                new CommandInput[] {  },
                "[]",
                "[{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "dev_benchmark"));
            commands.Add(new CommandDefinition(
                "dev.bug_report", "Dev",
                "Dev Bug Report", "dev.bug_report",
                CommandStatus.Implemented, "Run facman dev bug-report --json", "",
                "command.dev.bug_report.title", "command.dev.bug_report.description",
                "available", "read_only",
                false,
                new string[] { "workspace_read" },
                new CommandInput[] {  },
                "[]",
                "[{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "dev_bug_report"));
            commands.Add(new CommandDefinition(
                "dev.dump_data", "Dev",
                "Dev Dump Data", "dev.dump_data",
                CommandStatus.NotSupportedWithReason, "Run facman dev dump-data --json", "execution_not_enabled",
                "command.dev.dump_data.title", "command.dev.dump_data.description",
                "unavailable_until_isolation_proof", "process_execution",
                false,
                new string[] { "process_execute" },
                new CommandInput[] {  },
                "[]",
                "[{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "dev_dump_data"));
            commands.Add(new CommandDefinition(
                "dev.dump_icons", "Dev",
                "Dev Dump Icons", "dev.dump_icons",
                CommandStatus.NotSupportedWithReason, "Run facman dev dump-icons --json", "execution_not_enabled",
                "command.dev.dump_icons.title", "command.dev.dump_icons.description",
                "unavailable_until_isolation_proof", "process_execution",
                false,
                new string[] { "process_execute" },
                new CommandInput[] {  },
                "[]",
                "[{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "dev_dump_icons"));
            commands.Add(new CommandDefinition(
                "dev.instrument_mod", "Dev",
                "Dev Instrument Mod", "dev.instrument_mod",
                CommandStatus.NotSupportedWithReason, "Run facman dev instrument-mod --json", "execution_not_enabled",
                "command.dev.instrument_mod.title", "command.dev.instrument_mod.description",
                "unavailable_until_isolation_proof", "process_execution",
                false,
                new string[] { "process_execute" },
                new CommandInput[] {  },
                "[]",
                "[{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "dev_instrument_mod"));
            commands.Add(new CommandDefinition(
                "diagnostics.export", "Diagnostics",
                "Diagnostics Export", "diagnostics.export",
                CommandStatus.Implemented, "Run facman diagnostics export --instance <instance-id> --out <bundle.zip> --json", "",
                "command.diagnostics.export.title", "command.diagnostics.export.description",
                "available", "persistent_local_write",
                false,
                new string[] { "workspace_read", "workspace_write" },
                new CommandInput[] { new CommandInput("instance_id", "Instance ID", true, "identifier", false, "instance_id", null), new CommandInput("output_path", "Output Path", true, "path", false, "output_path", null) },
                "[]",
                "[{\"name\":\"--instance\",\"value\":\"instance-id\",\"repeatable\":false},{\"name\":\"--out\",\"value\":\"bundle.zip\",\"repeatable\":false},{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "diagnostics_export"));
            commands.Add(new CommandDefinition(
                "diagnostics.redact", "Diagnostics",
                "Diagnostics Redact", "diagnostics.redact",
                CommandStatus.Implemented, "Run facman diagnostics redact <path> --json", "",
                "command.diagnostics.redact.title", "command.diagnostics.redact.description",
                "available", "read_only",
                false,
                new string[] { "workspace_read" },
                new CommandInput[] { new CommandInput("path", "Path", true, "path", false, "path", null) },
                "[{\"name\":\"path\",\"required\":true}]",
                "[{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "diagnostics_redact"));
            commands.Add(new CommandDefinition(
                "doctor.explain", "Doctor",
                "Doctor Explain", "doctor.explain",
                CommandStatus.Implemented, "Run facman doctor explain --json", "",
                "command.doctor.explain.title", "command.doctor.explain.description",
                "available", "read_only",
                true,
                new string[] { "workspace_read" },
                new CommandInput[] {  },
                "[]",
                "[{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "doctor_explain"));
            commands.Add(new CommandDefinition(
                "doctor.run", "Doctor",
                "Doctor Run", "doctor.run",
                CommandStatus.Implemented, "Run facman doctor --json", "",
                "command.doctor.run.title", "command.doctor.run.description",
                "available", "read_only",
                true,
                new string[] { "workspace_read" },
                new CommandInput[] { new CommandInput("roots", "Roots", false, "string_array", true, "roots", null) },
                "[]",
                "[{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "doctor_run"));
            commands.Add(new CommandDefinition(
                "factorio.product.inspect", "Factorio",
                "Factorio Product Inspect", "factorio.product.inspect",
                CommandStatus.Implemented, "Run FLB command bridge: factorio.product.inspect", "",
                "command.factorio.product.inspect.title", "command.factorio.product.inspect.description",
                "available", "read_only",
                true,
                new string[] { "none" },
                new CommandInput[] {  },
                "[]",
                "[]",
                "product_inspect"));
            commands.Add(new CommandDefinition(
                "install_refs.list", "Install Refs",
                "Install Refs List", "install_refs.list",
                CommandStatus.Implemented, "Run facman installs list --json", "",
                "command.install_refs.list.title", "command.install_refs.list.description",
                "available", "read_only",
                true,
                new string[] { "workspace_read" },
                new CommandInput[] {  },
                "[]",
                "[{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "install_list"));
            commands.Add(new CommandDefinition(
                "installs.import", "Install Refs",
                "Installs Import", "install_refs.import",
                CommandStatus.Implemented, "Run facman installs import <factorio-dir> --id <install-id> --json", "",
                "command.install_refs.import.title", "command.install_refs.import.description",
                "available", "persistent_local_write",
                false,
                new string[] { "workspace_read", "workspace_write" },
                new CommandInput[] { new CommandInput("path", "Path", true, "path", false, "path", null), new CommandInput("install_id", "Install ID", true, "identifier", false, "install_id", null) },
                "[{\"name\":\"factorio-dir\",\"required\":true}]",
                "[{\"name\":\"--id\",\"value\":\"install-id\",\"repeatable\":false},{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "install_import"));
            commands.Add(new CommandDefinition(
                "installs.inspect", "Install Refs",
                "Installs Inspect", "install_refs.inspect",
                CommandStatus.Implemented, "Run facman installs inspect <install-id> --json", "",
                "command.install_refs.inspect.title", "command.install_refs.inspect.description",
                "available", "read_only",
                true,
                new string[] { "workspace_read" },
                new CommandInput[] { new CommandInput("install_id", "Install ID", true, "identifier", false, "install_id", null) },
                "[{\"name\":\"install-id\",\"required\":true}]",
                "[{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "install_inspect"));
            commands.Add(new CommandDefinition(
                "installs.install_version", "Installs",
                "Installs Install Version", "installs.install_version",
                CommandStatus.NotSupportedWithReason, "Run facman installs install-version <version> --archive <path> --json", "setup_plan_inputs_not_confirmed",
                "command.installs.install_version.title", "command.installs.install_version.description",
                "unavailable_until_gateway", "read_only",
                false,
                new string[] { "setup_preview" },
                new CommandInput[] { new CommandInput("version", "Version", true, "string", false, "version", null), new CommandInput("archive", "Archive", false, "path", false, "archive", null) },
                "[{\"name\":\"version\",\"required\":true}]",
                "[{\"name\":\"--archive\",\"value\":\"path\",\"repeatable\":false},{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "installs_install_version"));
            commands.Add(new CommandDefinition(
                "installs.repair", "Installs",
                "Installs Repair", "installs.repair",
                CommandStatus.NotSupportedWithReason, "Run facman installs repair <install-id> --json", "ownership_denied",
                "command.installs.repair.title", "command.installs.repair.description",
                "unavailable_until_gateway", "read_only",
                false,
                new string[] { "setup_preview", "foreign_owned_refusal" },
                new CommandInput[] { new CommandInput("id", "ID", true, "identifier", false, "id", null) },
                "[{\"name\":\"install-id\",\"required\":true}]",
                "[{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "installs_repair"));
            commands.Add(new CommandDefinition(
                "installs.scan", "Install Refs",
                "Installs Scan", "install_refs.scan",
                CommandStatus.Implemented, "Run facman installs scan --json", "",
                "command.install_refs.scan.title", "command.install_refs.scan.description",
                "available", "read_only",
                true,
                new string[] { "workspace_read" },
                new CommandInput[] { new CommandInput("roots", "Roots", false, "string_array", true, "roots", null) },
                "[]",
                "[{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "install_scan"));
            commands.Add(new CommandDefinition(
                "installs.uninstall", "Installs",
                "Installs Uninstall", "installs.uninstall",
                CommandStatus.NotSupportedWithReason, "Run facman installs uninstall <install-id> --json", "ownership_denied",
                "command.installs.uninstall.title", "command.installs.uninstall.description",
                "unavailable_until_gateway", "read_only",
                false,
                new string[] { "setup_preview", "foreign_owned_refusal" },
                new CommandInput[] { new CommandInput("id", "ID", true, "identifier", false, "id", null) },
                "[{\"name\":\"install-id\",\"required\":true}]",
                "[{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "installs_uninstall"));
            commands.Add(new CommandDefinition(
                "installs.verify", "Installs",
                "Installs Verify", "installs.verify",
                CommandStatus.NotSupportedWithReason, "Run facman installs verify <install-id> --json", "setup_verification_not_implemented",
                "command.installs.verify.title", "command.installs.verify.description",
                "unavailable_until_gateway", "read_only",
                false,
                new string[] { "setup_preview" },
                new CommandInput[] { new CommandInput("id", "ID", true, "identifier", false, "id", null) },
                "[{\"name\":\"install-id\",\"required\":true}]",
                "[{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "installs_verify"));
            commands.Add(new CommandDefinition(
                "instance.export", "Instance",
                "Instance Export", "instance.export",
                CommandStatus.Implemented, "Run facman export instance <instance-id> <pack.zip> --json", "",
                "command.instance.export.title", "command.instance.export.description",
                "available", "persistent_local_write",
                false,
                new string[] { "workspace_read", "workspace_write" },
                new CommandInput[] { new CommandInput("instance_id", "Instance ID", true, "identifier", false, "instance_id", null), new CommandInput("output_path", "Output Path", true, "path", false, "output_path", null) },
                "[{\"name\":\"instance-id\",\"required\":true},{\"name\":\"pack.zip\",\"required\":true}]",
                "[{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "instance_export"));
            commands.Add(new CommandDefinition(
                "instance.import", "Instance",
                "Instance Import", "instance.import",
                CommandStatus.Implemented, "Run facman import instance <pack.zip> --json", "",
                "command.instance.import.title", "command.instance.import.description",
                "available", "persistent_local_write",
                false,
                new string[] { "workspace_read", "workspace_write" },
                new CommandInput[] { new CommandInput("source_path", "Source Path", true, "path", false, "source_path", null), new CommandInput("instance_id", "Instance ID", false, "identifier", false, "instance_id", null) },
                "[{\"name\":\"pack.zip\",\"required\":true}]",
                "[{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "instance_import"));
            commands.Add(new CommandDefinition(
                "instance.list", "Instance",
                "Instance List", "instance.list",
                CommandStatus.Implemented, "Run facman instances list --json", "",
                "command.instance.list.title", "command.instance.list.description",
                "available", "read_only",
                true,
                new string[] { "workspace_read" },
                new CommandInput[] {  },
                "[]",
                "[{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "instance_list"));
            commands.Add(new CommandDefinition(
                "instances.archive", "Instances",
                "Instances Archive", "instances.archive",
                CommandStatus.Implemented, "Run facman instances archive <instance-id> --json", "",
                "command.instances.archive.title", "command.instances.archive.description",
                "available", "persistent_local_write",
                false,
                new string[] { "workspace_read", "workspace_write" },
                new CommandInput[] { new CommandInput("instance_id", "Instance ID", true, "identifier", false, "instance_id", null) },
                "[{\"name\":\"instance-id\",\"required\":true}]",
                "[{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "instances_archive"));
            commands.Add(new CommandDefinition(
                "instances.clone", "Instances",
                "Instances Clone", "instances.clone",
                CommandStatus.Implemented, "Run facman instances clone <source-id> <destination-id> [--name <display-name>] [--install <install-id>] --json", "",
                "command.instances.clone.title", "command.instances.clone.description",
                "available", "persistent_local_write",
                false,
                new string[] { "workspace_read", "workspace_write" },
                new CommandInput[] { new CommandInput("source_instance_id", "Source Instance ID", true, "identifier", false, "source_instance_id", null), new CommandInput("destination_instance_id", "Destination Instance ID", true, "identifier", false, "destination_instance_id", null), new CommandInput("display_name", "Display Name", false, "string", false, "display_name", null), new CommandInput("install_ref", "Install Ref", false, "identifier", false, "install_ref", null) },
                "[{\"name\":\"source-id\",\"required\":true},{\"name\":\"destination-id\",\"required\":true}]",
                "[{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "instances_clone"));
            commands.Add(new CommandDefinition(
                "instances.create", "Instance",
                "Instances Create", "instance.create",
                CommandStatus.Implemented, "Run facman instances create <name> --install <install-id> --json", "",
                "command.instance.create.title", "command.instance.create.description",
                "available", "persistent_local_write",
                false,
                new string[] { "workspace_read", "workspace_write" },
                new CommandInput[] { new CommandInput("display_name", "Display Name", true, "string", false, "display_name", null), new CommandInput("instance_id", "Instance ID", true, "identifier", false, "instance_id", null), new CommandInput("install_id", "Install ID", true, "identifier", false, "install_id", null), new CommandInput("template_id", "Template ID", false, "identifier", false, "template_id", null) },
                "[{\"name\":\"name\",\"required\":true}]",
                "[{\"name\":\"--install\",\"value\":\"install-id\",\"repeatable\":false},{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "instance_create"));
            commands.Add(new CommandDefinition(
                "instances.diff", "Instances",
                "Instances Diff", "instances.diff",
                CommandStatus.Implemented, "Run facman instances diff <left-instance-id> <right-instance-or-snapshot> --json", "",
                "command.instances.diff.title", "command.instances.diff.description",
                "available", "read_only",
                true,
                new string[] { "workspace_read" },
                new CommandInput[] { new CommandInput("left_instance_id", "Left Instance ID", true, "identifier", false, "left_instance_id", null), new CommandInput("right_ref", "Right Ref", true, "string", false, "right_ref", null) },
                "[{\"name\":\"left-instance-id\",\"required\":true},{\"name\":\"right-instance-or-snapshot\",\"required\":true}]",
                "[{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "instances_diff"));
            commands.Add(new CommandDefinition(
                "instances.inspect", "Instances",
                "Instances Inspect", "instances.inspect",
                CommandStatus.Implemented, "Run facman instances inspect <instance-id> --json", "",
                "command.instances.inspect.title", "command.instances.inspect.description",
                "available", "read_only",
                true,
                new string[] { "workspace_read" },
                new CommandInput[] { new CommandInput("instance_id", "Instance ID", true, "identifier", false, "instance_id", null) },
                "[{\"name\":\"instance-id\",\"required\":true}]",
                "[{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "instances_inspect"));
            commands.Add(new CommandDefinition(
                "instances.rename", "Instances",
                "Instances Rename", "instances.rename",
                CommandStatus.Implemented, "Run facman instances rename <instance-id> --name <display-name> --json", "",
                "command.instances.rename.title", "command.instances.rename.description",
                "available", "persistent_local_write",
                false,
                new string[] { "workspace_read", "workspace_write" },
                new CommandInput[] { new CommandInput("instance_id", "Instance ID", true, "identifier", false, "instance_id", null), new CommandInput("display_name", "Display Name", true, "string", false, "display_name", null) },
                "[{\"name\":\"instance-id\",\"required\":true}]",
                "[{\"name\":\"--name\",\"value\":\"display-name\",\"repeatable\":false},{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "instances_rename"));
            commands.Add(new CommandDefinition(
                "instances.restore", "Instances",
                "Instances Restore", "instances.restore",
                CommandStatus.Implemented, "Run facman instances restore <archive-id> [--new-id <instance-id>] --json", "",
                "command.instances.restore.title", "command.instances.restore.description",
                "available", "persistent_local_write",
                false,
                new string[] { "workspace_read", "workspace_write" },
                new CommandInput[] { new CommandInput("archive_id", "Archive ID", true, "string", false, "archive_id", null), new CommandInput("new_instance_id", "New Instance ID", false, "identifier", false, "new_instance_id", null) },
                "[{\"name\":\"archive-id\",\"required\":true}]",
                "[{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "instances_restore"));
            commands.Add(new CommandDefinition(
                "instances.verify", "Instances",
                "Instances Verify", "instances.verify",
                CommandStatus.Implemented, "Run facman instances verify <instance-id> --json", "",
                "command.instances.verify.title", "command.instances.verify.description",
                "available", "read_only",
                true,
                new string[] { "workspace_read" },
                new CommandInput[] { new CommandInput("instance_id", "Instance ID", true, "identifier", false, "instance_id", null) },
                "[{\"name\":\"instance-id\",\"required\":true}]",
                "[{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "instances_verify"));
            commands.Add(new CommandDefinition(
                "launch.plan", "Launch Plan",
                "Launch Plan", "launch_plan.build",
                CommandStatus.Implemented, "Run facman launch plan <instance-id> --json", "",
                "command.launch_plan.build.title", "command.launch_plan.build.description",
                "available", "read_only",
                true,
                new string[] { "workspace_read" },
                new CommandInput[] { new CommandInput("instance_id", "Instance ID", true, "identifier", false, "instance_id", null) },
                "[{\"name\":\"instance-id\",\"required\":true}]",
                "[{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "launch_plan_build"));
            commands.Add(new CommandDefinition(
                "launch_plan.explain", "Launch Plan",
                "Launch Plan Explain", "launch_plan.explain",
                CommandStatus.Implemented, "Run facman launch explain <instance-id> --json", "",
                "command.launch_plan.explain.title", "command.launch_plan.explain.description",
                "available", "read_only",
                true,
                new string[] { "workspace_read" },
                new CommandInput[] { new CommandInput("instance_id", "Instance ID", true, "identifier", false, "instance_id", null) },
                "[{\"name\":\"instance-id\",\"required\":true}]",
                "[{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "launch_plan_explain"));
            commands.Add(new CommandDefinition(
                "launch_plan.preflight", "Launch Plan",
                "Launch Plan Preflight", "launch_plan.preflight",
                CommandStatus.Implemented, "Run facman launch plan <instance-id> --preflight --json", "",
                "command.launch_plan.preflight.title", "command.launch_plan.preflight.description",
                "available", "read_only",
                true,
                new string[] { "workspace_read" },
                new CommandInput[] { new CommandInput("instance_id", "Instance ID", true, "identifier", false, "instance_id", null) },
                "[{\"name\":\"instance-id\",\"required\":true}]",
                "[{\"name\":\"--preflight\",\"value\":null,\"repeatable\":false},{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "launch_plan_preflight"));
            commands.Add(new CommandDefinition(
                "mods.import", "Mods",
                "Mods Import", "mods.import",
                CommandStatus.Implemented, "Run facman mods import <mod.zip> --instance <instance-id> --json", "",
                "command.mods.import.title", "command.mods.import.description",
                "available", "persistent_local_write",
                false,
                new string[] { "workspace_read", "workspace_write" },
                new CommandInput[] { new CommandInput("source_path", "Source Path", true, "path", false, "source_path", null), new CommandInput("instance_id", "Instance ID", true, "identifier", false, "instance_id", null) },
                "[{\"name\":\"mod.zip\",\"required\":true}]",
                "[{\"name\":\"--instance\",\"value\":\"instance-id\",\"repeatable\":false},{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "mods_import"));
            commands.Add(new CommandDefinition(
                "mods.install", "Mods",
                "Mods Install", "mods.install",
                CommandStatus.NotSupportedWithReason, "Run facman mods install <name> --instance <id> --json", "network_forbidden",
                "command.mods.install.title", "command.mods.install.description",
                "unavailable_until_gateway", "read_only",
                false,
                new string[] { "network_read" },
                new CommandInput[] { new CommandInput("query", "Query", false, "string", false, "query", null), new CommandInput("instance_id", "Instance ID", false, "identifier", false, "instance_id", null) },
                "[{\"name\":\"name\",\"required\":true}]",
                "[{\"name\":\"--instance\",\"value\":\"id\",\"repeatable\":false},{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "mods_install"));
            commands.Add(new CommandDefinition(
                "mods.search", "Mods",
                "Mods Search", "mods.search",
                CommandStatus.NotSupportedWithReason, "Run facman mods search <query> --json", "network_forbidden",
                "command.mods.search.title", "command.mods.search.description",
                "unavailable_until_gateway", "read_only",
                false,
                new string[] { "network_read" },
                new CommandInput[] { new CommandInput("query", "Query", false, "string", false, "query", null) },
                "[{\"name\":\"query\",\"required\":true}]",
                "[{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "mods_search"));
            commands.Add(new CommandDefinition(
                "mods.update", "Mods",
                "Mods Update", "mods.update",
                CommandStatus.NotSupportedWithReason, "Run facman mods update --instance <id> --json", "network_forbidden",
                "command.mods.update.title", "command.mods.update.description",
                "unavailable_until_gateway", "read_only",
                false,
                new string[] { "network_read" },
                new CommandInput[] { new CommandInput("instance_id", "Instance ID", false, "identifier", false, "instance_id", null) },
                "[]",
                "[{\"name\":\"--instance\",\"value\":\"id\",\"repeatable\":false},{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "mods_update"));
            commands.Add(new CommandDefinition(
                "modsets.explain", "Modsets",
                "Modsets Explain", "modsets.explain",
                CommandStatus.Implemented, "Run facman modsets explain <instance-id> --json", "",
                "command.modsets.explain.title", "command.modsets.explain.description",
                "available", "read_only",
                true,
                new string[] { "workspace_read" },
                new CommandInput[] { new CommandInput("instance_id", "Instance ID", true, "identifier", false, "instance_id", null) },
                "[{\"name\":\"instance-id\",\"required\":true}]",
                "[{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "modsets_explain"));
            commands.Add(new CommandDefinition(
                "modsets.export", "Modsets",
                "Modsets Export", "modsets.export",
                CommandStatus.Implemented, "Run facman modsets export <instance-id> <pack.zip> --json", "",
                "command.modsets.export.title", "command.modsets.export.description",
                "available", "persistent_local_write",
                false,
                new string[] { "workspace_read", "workspace_write" },
                new CommandInput[] { new CommandInput("instance_id", "Instance ID", true, "identifier", false, "instance_id", null), new CommandInput("output_path", "Output Path", true, "path", false, "output_path", null) },
                "[{\"name\":\"instance-id\",\"required\":true},{\"name\":\"pack.zip\",\"required\":true}]",
                "[{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "modsets_export"));
            commands.Add(new CommandDefinition(
                "modsets.lock", "Modsets",
                "Modsets Lock", "modsets.lock",
                CommandStatus.Implemented, "Run facman modsets lock <instance-id> --json", "",
                "command.modsets.lock.title", "command.modsets.lock.description",
                "available", "persistent_local_write",
                false,
                new string[] { "workspace_read", "workspace_write" },
                new CommandInput[] { new CommandInput("instance_id", "Instance ID", true, "identifier", false, "instance_id", null) },
                "[{\"name\":\"instance-id\",\"required\":true}]",
                "[{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "modsets_lock"));
            commands.Add(new CommandDefinition(
                "modsets.verify", "Modsets",
                "Modsets Verify", "modsets.verify",
                CommandStatus.Implemented, "Run facman modsets verify <instance-id> --json", "",
                "command.modsets.verify.title", "command.modsets.verify.description",
                "available", "read_only",
                true,
                new string[] { "workspace_read" },
                new CommandInput[] { new CommandInput("instance_id", "Instance ID", true, "identifier", false, "instance_id", null) },
                "[{\"name\":\"instance-id\",\"required\":true}]",
                "[{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "modsets_verify"));
            commands.Add(new CommandDefinition(
                "onboarding.plan", "Onboarding",
                "Onboarding Plan", "onboarding.plan",
                CommandStatus.Implemented, "Run facman onboarding plan --preferred-install <install-id> --name <display-name> --template <template-id> --json", "",
                "command.onboarding.plan.title", "command.onboarding.plan.description",
                "available", "read_only",
                true,
                new string[] { "workspace_read" },
                new CommandInput[] { new CommandInput("preferred_install", "Preferred Install", false, "identifier", false, "preferred_install", null), new CommandInput("instance_display_name", "Instance Display Name", false, "string", false, "instance_display_name", null), new CommandInput("template_id", "Template ID", false, "identifier", false, "template_id", null), new CommandInput("workspace", "Workspace", false, "path", false, "workspace", null) },
                "[]",
                "[{\"name\":\"--preferred-install\",\"value\":\"install-id\",\"repeatable\":false},{\"name\":\"--name\",\"value\":\"display-name\",\"repeatable\":false},{\"name\":\"--template\",\"value\":\"template-id\",\"repeatable\":false},{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "onboarding_plan"));
            commands.Add(new CommandDefinition(
                "package.verify", "Package",
                "Package Verify", "package.verify",
                CommandStatus.NotSupportedWithReason, "Run facman package verify --json", "setup_unavailable",
                "command.package.verify.title", "command.package.verify.description",
                "unavailable_until_gateway", "read_only",
                false,
                new string[] { "setup_preview" },
                new CommandInput[] { new CommandInput("path", "Path", false, "path", false, "path", null) },
                "[]",
                "[{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "package_verify"));
            commands.Add(new CommandDefinition(
                "preferences.apply", "Preferences",
                "Preferences Apply", "preferences.apply",
                CommandStatus.Implemented, "Run facman preferences apply --json", "",
                "command.preferences.apply.title", "command.preferences.apply.description",
                "available", "persistent_local_write",
                false,
                new string[] { "workspace_read", "workspace_write" },
                new CommandInput[] { new CommandInput("preferred_workspace", "Preferred Workspace", false, "path", false, "preferred_workspace", null), new CommandInput("preferred_transport", "Preferred Transport", false, "enum", false, "preferred_transport", null), new CommandInput("default_instance_template", "Default Instance Template", false, "identifier", false, "default_instance_template", null), new CommandInput("default_launch_profile", "Default Launch Profile", false, "identifier", false, "default_launch_profile", null), new CommandInput("display_color_policy", "Display Color Policy", false, "enum", false, "display_color_policy", null), new CommandInput("tui_page_size", "Tui Page Size", false, "string", false, "tui_page_size", null), new CommandInput("command_timeout_seconds", "Command Timeout Seconds", false, "string", false, "command_timeout_seconds", null), new CommandInput("backup_destination", "Backup Destination", false, "path", false, "backup_destination", null), new CommandInput("backup_keep_last", "Backup Keep Last", false, "string", false, "backup_keep_last", null), new CommandInput("discovery_providers", "Discovery Providers", false, "string_array", true, "discovery_providers", null), new CommandInput("discovery_roots", "Discovery Roots", false, "string_array", true, "discovery_roots", null) },
                "[]",
                "[{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "preferences_apply"));
            commands.Add(new CommandDefinition(
                "preferences.inspect", "Preferences",
                "Preferences Inspect", "preferences.inspect",
                CommandStatus.Implemented, "Run facman preferences inspect --json", "",
                "command.preferences.inspect.title", "command.preferences.inspect.description",
                "available", "read_only",
                true,
                new string[] { "workspace_read" },
                new CommandInput[] {  },
                "[]",
                "[{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "preferences_inspect"));
            commands.Add(new CommandDefinition(
                "preferences.plan", "Preferences",
                "Preferences Plan", "preferences.plan",
                CommandStatus.Implemented, "Run facman preferences plan --json", "",
                "command.preferences.plan.title", "command.preferences.plan.description",
                "available", "read_only",
                true,
                new string[] { "workspace_read" },
                new CommandInput[] { new CommandInput("preferred_workspace", "Preferred Workspace", false, "path", false, "preferred_workspace", null), new CommandInput("preferred_transport", "Preferred Transport", false, "enum", false, "preferred_transport", null), new CommandInput("default_instance_template", "Default Instance Template", false, "identifier", false, "default_instance_template", null), new CommandInput("default_launch_profile", "Default Launch Profile", false, "identifier", false, "default_launch_profile", null), new CommandInput("display_color_policy", "Display Color Policy", false, "enum", false, "display_color_policy", null), new CommandInput("tui_page_size", "Tui Page Size", false, "string", false, "tui_page_size", null), new CommandInput("command_timeout_seconds", "Command Timeout Seconds", false, "string", false, "command_timeout_seconds", null), new CommandInput("backup_destination", "Backup Destination", false, "path", false, "backup_destination", null), new CommandInput("backup_keep_last", "Backup Keep Last", false, "string", false, "backup_keep_last", null), new CommandInput("discovery_providers", "Discovery Providers", false, "string_array", true, "discovery_providers", null), new CommandInput("discovery_roots", "Discovery Roots", false, "string_array", true, "discovery_roots", null) },
                "[]",
                "[{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "preferences_plan"));
            commands.Add(new CommandDefinition(
                "preferences.reset.apply", "Preferences",
                "Preferences Reset Apply", "preferences.reset.apply",
                CommandStatus.Implemented, "Run facman preferences reset apply --json", "",
                "command.preferences.reset.apply.title", "command.preferences.reset.apply.description",
                "available", "persistent_local_write",
                false,
                new string[] { "workspace_read", "workspace_write" },
                new CommandInput[] {  },
                "[]",
                "[{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "preferences_reset_apply"));
            commands.Add(new CommandDefinition(
                "preferences.reset.plan", "Preferences",
                "Preferences Reset Plan", "preferences.reset.plan",
                CommandStatus.Implemented, "Run facman preferences reset plan --json", "",
                "command.preferences.reset.plan.title", "command.preferences.reset.plan.description",
                "available", "read_only",
                true,
                new string[] { "workspace_read" },
                new CommandInput[] {  },
                "[]",
                "[{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "preferences_reset_plan"));
            commands.Add(new CommandDefinition(
                "preferences.validate", "Preferences",
                "Preferences Validate", "preferences.validate",
                CommandStatus.Implemented, "Run facman preferences validate --json", "",
                "command.preferences.validate.title", "command.preferences.validate.description",
                "available", "read_only",
                true,
                new string[] { "workspace_read" },
                new CommandInput[] { new CommandInput("preferred_workspace", "Preferred Workspace", false, "path", false, "preferred_workspace", null), new CommandInput("preferred_transport", "Preferred Transport", false, "enum", false, "preferred_transport", null), new CommandInput("default_instance_template", "Default Instance Template", false, "identifier", false, "default_instance_template", null), new CommandInput("default_launch_profile", "Default Launch Profile", false, "identifier", false, "default_launch_profile", null), new CommandInput("display_color_policy", "Display Color Policy", false, "enum", false, "display_color_policy", null), new CommandInput("tui_page_size", "Tui Page Size", false, "string", false, "tui_page_size", null), new CommandInput("command_timeout_seconds", "Command Timeout Seconds", false, "string", false, "command_timeout_seconds", null), new CommandInput("backup_destination", "Backup Destination", false, "path", false, "backup_destination", null), new CommandInput("backup_keep_last", "Backup Keep Last", false, "string", false, "backup_keep_last", null), new CommandInput("discovery_providers", "Discovery Providers", false, "string_array", true, "discovery_providers", null), new CommandInput("discovery_roots", "Discovery Roots", false, "string_array", true, "discovery_roots", null) },
                "[]",
                "[{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "preferences_validate"));
            commands.Add(new CommandDefinition(
                "product.inspect", "Product",
                "Product Inspect", "product.inspect",
                CommandStatus.Implemented, "Run facman product inspect --json", "",
                "command.product.inspect.title", "command.product.inspect.description",
                "available", "read_only",
                true,
                new string[] { "none" },
                new CommandInput[] {  },
                "[]",
                "[{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "product_inspect"));
            commands.Add(new CommandDefinition(
                "run.execute", "Run",
                "Run Execute", "run.execute",
                CommandStatus.NotSupportedWithReason, "Run facman run <instance-id> --execute --json", "isolation_not_proven",
                "command.run.execute.title", "command.run.execute.description",
                "unavailable_until_isolation_proof", "read_only",
                false,
                new string[] { "workspace_read" },
                new CommandInput[] { new CommandInput("instance_id", "Instance ID", false, "identifier", false, "instance_id", null) },
                "[{\"name\":\"instance-id\",\"required\":true}]",
                "[{\"name\":\"--execute\",\"value\":null,\"repeatable\":false},{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "run_execute"));
            commands.Add(new CommandDefinition(
                "run.preview", "Run",
                "Run Preview", "run.preview",
                CommandStatus.Implemented, "Run facman run <instance-id> --json", "",
                "command.run.preview.title", "command.run.preview.description",
                "available", "read_only",
                true,
                new string[] { "workspace_read" },
                new CommandInput[] { new CommandInput("instance_id", "Instance ID", true, "identifier", false, "instance_id", null) },
                "[{\"name\":\"instance-id\",\"required\":true}]",
                "[{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "run_preview"));
            commands.Add(new CommandDefinition(
                "saves.backup", "Saves",
                "Saves Backup", "saves.backup",
                CommandStatus.Implemented, "Run facman saves backup <save> --instance <instance-id> --json", "",
                "command.saves.backup.title", "command.saves.backup.description",
                "available", "persistent_local_write",
                false,
                new string[] { "workspace_read", "workspace_write" },
                new CommandInput[] { new CommandInput("instance_id", "Instance ID", true, "identifier", false, "instance_id", null), new CommandInput("save", "Save", true, "string", false, "save", null), new CommandInput("output_path", "Output Path", false, "path", false, "output_path", null) },
                "[{\"name\":\"save\",\"required\":true}]",
                "[{\"name\":\"--instance\",\"value\":\"instance-id\",\"repeatable\":false},{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "saves_backup"));
            commands.Add(new CommandDefinition(
                "saves.clone", "Saves",
                "Saves Clone", "saves.clone",
                CommandStatus.Implemented, "Run facman saves clone <save> --instance <source-id> --to-instance <target-id> --json", "",
                "command.saves.clone.title", "command.saves.clone.description",
                "available", "persistent_local_write",
                false,
                new string[] { "workspace_read", "workspace_write" },
                new CommandInput[] { new CommandInput("source_instance_id", "Source Instance ID", true, "identifier", false, "source_instance_id", null), new CommandInput("target_instance_id", "Target Instance ID", true, "identifier", false, "target_instance_id", null), new CommandInput("save", "Save", true, "string", false, "save", null) },
                "[{\"name\":\"save\",\"required\":true}]",
                "[{\"name\":\"--instance\",\"value\":\"source-id\",\"repeatable\":false},{\"name\":\"--to-instance\",\"value\":\"target-id\",\"repeatable\":false},{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "saves_clone"));
            commands.Add(new CommandDefinition(
                "saves.list", "Saves",
                "Saves List", "saves.list",
                CommandStatus.Implemented, "Run facman saves list --instance <instance-id> --json", "",
                "command.saves.list.title", "command.saves.list.description",
                "available", "read_only",
                true,
                new string[] { "workspace_read" },
                new CommandInput[] { new CommandInput("instance_id", "Instance ID", true, "identifier", false, "instance_id", null) },
                "[]",
                "[{\"name\":\"--instance\",\"value\":\"instance-id\",\"repeatable\":false},{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "saves_list"));
            commands.Add(new CommandDefinition(
                "servers.create", "Servers",
                "Servers Create", "servers.create",
                CommandStatus.Implemented, "Run facman servers create <name> --instance <id> --json", "",
                "command.servers.create.title", "command.servers.create.description",
                "available", "persistent_local_write",
                false,
                new string[] { "workspace_read", "workspace_write" },
                new CommandInput[] { new CommandInput("name", "Name", true, "string", false, "name", null), new CommandInput("id", "ID", false, "identifier", false, "id", null), new CommandInput("instance_id", "Instance ID", true, "identifier", false, "instance_id", null) },
                "[{\"name\":\"name\",\"required\":true}]",
                "[{\"name\":\"--instance\",\"value\":\"id\",\"repeatable\":false},{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "servers_create"));
            commands.Add(new CommandDefinition(
                "servers.list", "Servers",
                "Servers List", "servers.list",
                CommandStatus.Implemented, "Run facman servers list --json", "",
                "command.servers.list.title", "command.servers.list.description",
                "available", "read_only",
                false,
                new string[] { "workspace_read" },
                new CommandInput[] {  },
                "[]",
                "[{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "servers_list"));
            commands.Add(new CommandDefinition(
                "servers.rcon", "Servers",
                "Servers RCON", "servers.rcon",
                CommandStatus.NotSupportedWithReason, "Run facman servers rcon <server-id> --json", "execution_not_enabled",
                "command.servers.rcon.title", "command.servers.rcon.description",
                "unavailable_until_isolation_proof", "process_execution",
                false,
                new string[] { "workspace_read", "process_execute" },
                new CommandInput[] { new CommandInput("id", "ID", true, "identifier", false, "id", null) },
                "[{\"name\":\"server-id\",\"required\":true}]",
                "[{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "servers_rcon"));
            commands.Add(new CommandDefinition(
                "servers.start", "Servers",
                "Servers Start", "servers.start",
                CommandStatus.NotSupportedWithReason, "Run facman servers start <server-id> --json", "execution_not_enabled",
                "command.servers.start.title", "command.servers.start.description",
                "unavailable_until_isolation_proof", "process_execution",
                false,
                new string[] { "workspace_read", "process_execute" },
                new CommandInput[] { new CommandInput("id", "ID", true, "identifier", false, "id", null) },
                "[{\"name\":\"server-id\",\"required\":true}]",
                "[{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "servers_start"));
            commands.Add(new CommandDefinition(
                "servers.stop", "Servers",
                "Servers Stop", "servers.stop",
                CommandStatus.NotSupportedWithReason, "Run facman servers stop <server-id> --json", "execution_not_enabled",
                "command.servers.stop.title", "command.servers.stop.description",
                "unavailable_until_isolation_proof", "process_execution",
                false,
                new string[] { "workspace_read", "process_execute" },
                new CommandInput[] { new CommandInput("id", "ID", true, "identifier", false, "id", null) },
                "[{\"name\":\"server-id\",\"required\":true}]",
                "[{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "servers_stop"));
            commands.Add(new CommandDefinition(
                "setup.preview", "Setup",
                "Setup Preview", "setup.preview",
                CommandStatus.NotSupportedWithReason, "Run facman setup preview --json", "setup_unavailable",
                "command.setup.preview.title", "command.setup.preview.description",
                "unavailable_until_gateway", "read_only",
                true,
                new string[] { "workspace_read" },
                new CommandInput[] {  },
                "[]",
                "[{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "setup_preview"));
            commands.Add(new CommandDefinition(
                "snapshots.create", "Snapshots",
                "Snapshots Create", "snapshots.create",
                CommandStatus.Implemented, "Run facman snapshots create <instance-id> <snapshot-id> [--save <name>] --json", "",
                "command.snapshots.create.title", "command.snapshots.create.description",
                "available", "persistent_local_write",
                true,
                new string[] { "workspace_read", "workspace_write" },
                new CommandInput[] { new CommandInput("instance_id", "Instance ID", true, "identifier", false, "instance_id", null), new CommandInput("snapshot_id", "Snapshot ID", true, "identifier", false, "snapshot_id", null), new CommandInput("saves", "Saves", false, "string_array", true, "saves", null) },
                "[{\"name\":\"instance-id\",\"required\":true},{\"name\":\"snapshot-id\",\"required\":true}]",
                "[{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "snapshots_create"));
            commands.Add(new CommandDefinition(
                "snapshots.diff", "Snapshots",
                "Snapshots Diff", "snapshots.diff",
                CommandStatus.Implemented, "Run facman snapshots diff <instance-id> <left-id> <right-id> --json", "",
                "command.snapshots.diff.title", "command.snapshots.diff.description",
                "available", "read_only",
                true,
                new string[] { "workspace_read" },
                new CommandInput[] { new CommandInput("instance_id", "Instance ID", true, "identifier", false, "instance_id", null), new CommandInput("left_snapshot_id", "Left Snapshot ID", true, "identifier", false, "left_snapshot_id", null), new CommandInput("right_snapshot_id", "Right Snapshot ID", true, "identifier", false, "right_snapshot_id", null) },
                "[{\"name\":\"instance-id\",\"required\":true},{\"name\":\"left-id\",\"required\":true},{\"name\":\"right-id\",\"required\":true}]",
                "[{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "snapshots_diff"));
            commands.Add(new CommandDefinition(
                "snapshots.inspect", "Snapshots",
                "Snapshots Inspect", "snapshots.inspect",
                CommandStatus.Implemented, "Run facman snapshots inspect <instance-id> <snapshot-id> --json", "",
                "command.snapshots.inspect.title", "command.snapshots.inspect.description",
                "available", "read_only",
                true,
                new string[] { "workspace_read" },
                new CommandInput[] { new CommandInput("instance_id", "Instance ID", true, "identifier", false, "instance_id", null), new CommandInput("snapshot_id", "Snapshot ID", true, "identifier", false, "snapshot_id", null) },
                "[{\"name\":\"instance-id\",\"required\":true},{\"name\":\"snapshot-id\",\"required\":true}]",
                "[{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "snapshots_inspect"));
            commands.Add(new CommandDefinition(
                "snapshots.list", "Snapshots",
                "Snapshots List", "snapshots.list",
                CommandStatus.Implemented, "Run facman snapshots list <instance-id> --json", "",
                "command.snapshots.list.title", "command.snapshots.list.description",
                "available", "read_only",
                true,
                new string[] { "workspace_read" },
                new CommandInput[] { new CommandInput("instance_id", "Instance ID", true, "identifier", false, "instance_id", null) },
                "[{\"name\":\"instance-id\",\"required\":true}]",
                "[{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "snapshots_list"));
            commands.Add(new CommandDefinition(
                "snapshots.restore", "Snapshots",
                "Snapshots Restore", "snapshots.restore",
                CommandStatus.Implemented, "Run facman snapshots restore <snapshot-path> <target-instance-id> --json", "",
                "command.snapshots.restore.title", "command.snapshots.restore.description",
                "available", "persistent_local_write",
                true,
                new string[] { "workspace_read", "workspace_write" },
                new CommandInput[] { new CommandInput("snapshot_ref", "Snapshot Ref", true, "path", false, "snapshot_ref", null), new CommandInput("target_instance_id", "Target Instance ID", true, "identifier", false, "target_instance_id", null) },
                "[{\"name\":\"snapshot-path\",\"required\":true},{\"name\":\"target-instance-id\",\"required\":true}]",
                "[{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "snapshots_restore"));
            commands.Add(new CommandDefinition(
                "snapshots.retention.apply", "Snapshots",
                "Snapshots Retention Apply", "snapshots.retention.apply",
                CommandStatus.Implemented, "Run facman snapshots retention apply <instance-id> [--keep-last <count>] [--keep-daily <count>] [--keep-weekly <count>] [--maximum-total-bytes <bytes>] [--minimum-age-days <days>] --json", "",
                "command.snapshots.retention.apply.title", "command.snapshots.retention.apply.description",
                "available", "persistent_local_write",
                true,
                new string[] { "workspace_read", "workspace_write" },
                new CommandInput[] { new CommandInput("instance_id", "Instance ID", true, "identifier", false, "instance_id", null), new CommandInput("keep_last", "Keep Last", false, "string", false, "keep_last", null), new CommandInput("keep_daily", "Keep Daily", false, "string", false, "keep_daily", null), new CommandInput("keep_weekly", "Keep Weekly", false, "string", false, "keep_weekly", null), new CommandInput("maximum_total_bytes", "Maximum Total Bytes", false, "string", false, "maximum_total_bytes", null), new CommandInput("minimum_age_days", "Minimum Age Days", false, "string", false, "minimum_age_days", null) },
                "[{\"name\":\"instance-id\",\"required\":true}]",
                "[{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "snapshots_retention_apply"));
            commands.Add(new CommandDefinition(
                "snapshots.retention.plan", "Snapshots",
                "Snapshots Retention Plan", "snapshots.retention.plan",
                CommandStatus.Implemented, "Run facman snapshots retention plan <instance-id> [--keep-last <count>] [--keep-daily <count>] [--keep-weekly <count>] [--maximum-total-bytes <bytes>] [--minimum-age-days <days>] --json", "",
                "command.snapshots.retention.plan.title", "command.snapshots.retention.plan.description",
                "available", "read_only",
                true,
                new string[] { "workspace_read" },
                new CommandInput[] { new CommandInput("instance_id", "Instance ID", true, "identifier", false, "instance_id", null), new CommandInput("keep_last", "Keep Last", false, "string", false, "keep_last", null), new CommandInput("keep_daily", "Keep Daily", false, "string", false, "keep_daily", null), new CommandInput("keep_weekly", "Keep Weekly", false, "string", false, "keep_weekly", null), new CommandInput("maximum_total_bytes", "Maximum Total Bytes", false, "string", false, "maximum_total_bytes", null), new CommandInput("minimum_age_days", "Minimum Age Days", false, "string", false, "minimum_age_days", null) },
                "[{\"name\":\"instance-id\",\"required\":true}]",
                "[{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "snapshots_retention_plan"));
            commands.Add(new CommandDefinition(
                "snapshots.verify", "Snapshots",
                "Snapshots Verify", "snapshots.verify",
                CommandStatus.Implemented, "Run facman snapshots verify <instance-id> <snapshot-id> --json", "",
                "command.snapshots.verify.title", "command.snapshots.verify.description",
                "available", "read_only",
                true,
                new string[] { "workspace_read" },
                new CommandInput[] { new CommandInput("instance_id", "Instance ID", true, "identifier", false, "instance_id", null), new CommandInput("snapshot_id", "Snapshot ID", true, "identifier", false, "snapshot_id", null) },
                "[{\"name\":\"instance-id\",\"required\":true},{\"name\":\"snapshot-id\",\"required\":true}]",
                "[{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "snapshots_verify"));
            commands.Add(new CommandDefinition(
                "workspace.migration.apply", "Workspace",
                "Workspace Migration Apply", "workspace.migration.apply",
                CommandStatus.Implemented, "Run facman workspace migration apply --json", "",
                "command.workspace.migration.apply.title", "command.workspace.migration.apply.description",
                "available", "persistent_local_write",
                false,
                new string[] { "workspace_read", "workspace_write" },
                new CommandInput[] {  },
                "[]",
                "[{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "migration_apply"));
            commands.Add(new CommandDefinition(
                "workspace.migration.inspect", "Workspace",
                "Workspace Migration Inspect", "workspace.migration.inspect",
                CommandStatus.Implemented, "Run facman workspace migration inspect --json", "",
                "command.workspace.migration.inspect.title", "command.workspace.migration.inspect.description",
                "available", "read_only",
                true,
                new string[] { "workspace_read" },
                new CommandInput[] {  },
                "[]",
                "[{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "migration_inspect"));
            commands.Add(new CommandDefinition(
                "workspace.migration.plan", "Workspace",
                "Workspace Migration Plan", "workspace.migration.plan",
                CommandStatus.Implemented, "Run facman workspace migration plan --json", "",
                "command.workspace.migration.plan.title", "command.workspace.migration.plan.description",
                "available", "read_only",
                true,
                new string[] { "workspace_read" },
                new CommandInput[] {  },
                "[]",
                "[{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "migration_plan"));
            commands.Add(new CommandDefinition(
                "workspace.paths", "Workspace",
                "Workspace Paths", "workspace.paths",
                CommandStatus.Implemented, "Run facman workspace paths --json", "",
                "command.workspace.paths.title", "command.workspace.paths.description",
                "available", "read_only",
                true,
                new string[] { "workspace_read" },
                new CommandInput[] {  },
                "[]",
                "[{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "workspace_paths"));
            commands.Add(new CommandDefinition(
                "workspace.recovery.apply", "Workspace",
                "Workspace Recovery Apply", "workspace.recovery.apply",
                CommandStatus.Implemented, "Run facman workspace recovery apply <transaction-id> --json", "",
                "command.workspace.recovery.apply.title", "command.workspace.recovery.apply.description",
                "available", "persistent_local_write",
                false,
                new string[] { "workspace_read", "workspace_write" },
                new CommandInput[] { new CommandInput("transaction_id", "Transaction ID", true, "identifier", false, "transaction_id", null) },
                "[{\"name\":\"transaction-id\",\"required\":true}]",
                "[{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "recovery_apply"));
            commands.Add(new CommandDefinition(
                "workspace.recovery.inspect", "Workspace",
                "Workspace Recovery Inspect", "workspace.recovery.inspect",
                CommandStatus.Implemented, "Run facman workspace recovery inspect --json", "",
                "command.workspace.recovery.inspect.title", "command.workspace.recovery.inspect.description",
                "available", "read_only",
                true,
                new string[] { "workspace_read" },
                new CommandInput[] {  },
                "[]",
                "[{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "recovery_inspect"));
            commands.Add(new CommandDefinition(
                "workspace.recovery.plan", "Workspace",
                "Workspace Recovery Plan", "workspace.recovery.plan",
                CommandStatus.Implemented, "Run facman workspace recovery plan <transaction-id> --json", "",
                "command.workspace.recovery.plan.title", "command.workspace.recovery.plan.description",
                "available", "read_only",
                true,
                new string[] { "workspace_read" },
                new CommandInput[] { new CommandInput("transaction_id", "Transaction ID", true, "identifier", false, "transaction_id", null) },
                "[{\"name\":\"transaction-id\",\"required\":true}]",
                "[{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "recovery_plan"));
            commands.Add(new CommandDefinition(
                "workspace.status", "Workspace",
                "Workspace Status", "workspace.status",
                CommandStatus.Implemented, "Run facman workspace status --json", "",
                "command.workspace.status.title", "command.workspace.status.description",
                "available", "read_only",
                true,
                new string[] { "workspace_read" },
                new CommandInput[] {  },
                "[]",
                "[{\"name\":\"--json\",\"value\":null,\"repeatable\":false}]",
                "workspace_status"));
            return commands.AsReadOnly();
        }
    }
}
