# SPDX-FileCopyrightText: 2026 Jules C
# SPDX-License-Identifier: MIT

from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
import tomllib
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

INDEX = ROOT / "contracts/command/factorio/index.v1.toml"
VERSION = ROOT / "release/index/version.v1.toml"
FRONTEND = ROOT / "contracts/command/frontend/frontend.required_commands.v1.toml"

OUTPUTS = {
    "catalog_json": ROOT / "contracts/generated-index/command_catalog.v1.json",
    "command_header": ROOT / "runtime/core/generated/command_catalog.h",
    "version_header": ROOT / "runtime/core/generated/version.h",
    "help_include": ROOT / "apps/cli/generated/command_help.inc",
    "bash": ROOT / "apps/cli/completions/facman.bash",
    "zsh": ROOT / "apps/cli/completions/_facman",
    "fish": ROOT / "apps/cli/completions/facman.fish",
    "powershell": ROOT / "apps/cli/completions/FacMan.ps1",
    "docs": ROOT / "docs/reference/generated-command-catalog.md",
}


def load_toml(path: Path) -> dict[str, Any]:
    with path.open("rb") as handle:
        return tomllib.load(handle)


def digest_source(digest: Any, path: Path) -> None:
    digest.update(path.relative_to(ROOT).as_posix().encode())
    digest.update(b"\0")
    digest.update(path.read_bytes().replace(b"\r\n", b"\n"))
    digest.update(b"\0")


def load_sources() -> tuple[dict[str, Any], dict[str, Any], list[dict[str, Any]], str]:
    index = load_toml(INDEX)
    version = load_toml(VERSION)
    if index.get("schema") != "facman.command_catalog_index.v1":
        raise ValueError("command catalog index has the wrong schema")
    if version.get("schema") != "facman.version.v1":
        raise ValueError("version index has the wrong schema")
    files = index.get("files", [])
    if not isinstance(files, list) or len(files) != len(set(files)):
        raise ValueError("command catalog files must be a unique array")
    runtime_ids = index.get("runtime_ids", {})
    registered = set(index.get("registered", []))
    commands: list[dict[str, Any]] = []
    digest = hashlib.sha256()
    for path in [INDEX, VERSION, FRONTEND]:
        digest_source(digest, path)
    for name in files:
        path = INDEX.parent / str(name)
        if not path.is_file():
            raise ValueError(f"indexed command contract does not exist: {path.relative_to(ROOT)}")
        data = load_toml(path)
        command_id = str(data.get("command_id", ""))
        if not command_id:
            raise ValueError(f"{path.relative_to(ROOT)} has no command_id")
        runtime_id = str(runtime_ids.get(command_id, command_id))
        item = dict(data)
        item["contract_path"] = path.relative_to(ROOT).as_posix()
        item["runtime_id"] = runtime_id
        item["registered"] = runtime_id in registered
        commands.append(item)
        digest_source(digest, path)
    ids = [str(item["command_id"]) for item in commands]
    runtime = [str(item["runtime_id"]) for item in commands]
    if len(ids) != len(set(ids)) or len(runtime) != len(set(runtime)):
        raise ValueError("command and runtime IDs must be unique")
    if registered - set(runtime):
        raise ValueError(f"registered runtime IDs are missing contracts: {sorted(registered - set(runtime))}")
    commands.sort(key=lambda item: str(item["command_id"]))
    return index, version, commands, digest.hexdigest()


def c_identifier(value: str) -> str:
    return re.sub(r"[^A-Za-z0-9]", "_", value).upper()


def c_string(value: str) -> str:
    return json.dumps(value)


def dry_run_behavior(item: dict[str, Any]) -> str:
    runtime_id = str(item["runtime_id"])
    effects = set(str(value) for value in item.get("effects", []))
    if runtime_id == "launch_plan.build":
        return "preview_only"
    if runtime_id == "launch_plan.preflight":
        return "read_only_no_process"
    if runtime_id == "run.preview":
        return "preview_only_no_process"
    if "workspace_write" in effects:
        return "explicit_persistent_write"
    return "read_only"


def runtime_availability(item: dict[str, Any]) -> str:
    availability = str(item.get("availability", "implemented"))
    return "available" if availability == "implemented" else availability


def render(index: dict[str, Any], version: dict[str, Any], commands: list[dict[str, Any]], digest: str) -> dict[str, str]:
    catalog = {
        "schema": "facman.generated_command_catalog.v1",
        "source_digest": digest,
        "owner": index["owner"],
        "binding": index["binding"],
        "version": version["canonical_version"],
        "commands": commands,
    }
    header = [
        f"/* Generated by tools/codegen/generate_metadata.py; source-sha256: {digest}. */",
        "#ifndef FACMAN_GENERATED_COMMAND_CATALOG_H",
        "#define FACMAN_GENERATED_COMMAND_CATALOG_H",
        "",
        "typedef enum facman_generated_command_id {",
    ]
    for item in commands:
        header.append(f"    FACMAN_COMMAND_{c_identifier(str(item['command_id']))},")
    header.extend([
        "    FACMAN_COMMAND_COUNT",
        "} facman_generated_command_id;",
        "",
        "typedef struct facman_generated_command_descriptor {",
        "    const char* command_name;",
        "    const char* effects_json;",
        "    const char* request_schema;",
        "    const char* response_schema;",
        "    const char* result_schema;",
        "    const char* refusal_schema;",
        "    const char* diagnostic_schema;",
        "    const char* dry_run_behavior;",
        "    const char* availability;",
        "    const char* owner;",
        "    const char* binding;",
        "} facman_generated_command_descriptor;",
        "",
        "static const facman_generated_command_descriptor facman_generated_registered_commands[] = {",
    ])
    for item in commands:
        if not item["registered"]:
            continue
        effects = json.dumps(item.get("effects", []), separators=(",", ":"))
        values = [
            str(item["runtime_id"]),
            effects,
            str(item["request_schema"]),
            str(item["response_schema"]),
            str(item["result_schema"]),
            str(item["refusal_schema"]),
            str(item["diagnostic_schema"]),
            dry_run_behavior(item),
            runtime_availability(item),
            str(index["owner"]),
            str(index["binding"]),
        ]
        header.append("    {")
        header.extend(f"        {c_string(value)}," for value in values)
        header.append("    },")
    header.extend([
        "};",
        "#define FACMAN_GENERATED_REGISTERED_COMMAND_COUNT \\",
        "    (sizeof(facman_generated_registered_commands) / sizeof(facman_generated_registered_commands[0]))",
        "",
        "#endif",
        "",
    ])
    version_header = [
        f"/* Generated by tools/codegen/generate_metadata.py; source-sha256: {digest}. */",
        "#ifndef FACMAN_GENERATED_VERSION_H",
        "#define FACMAN_GENERATED_VERSION_H",
        f"#define FACMAN_VERSION_SEMVER {c_string(str(version['semver']))}",
        f"#define FACMAN_VERSION_CANONICAL {c_string(str(version['canonical_version']))}",
        f"#define FACMAN_VERSION_FILENAME {c_string(str(version['filename_version']))}",
        f"#define FACMAN_VERSION_COMPONENT {c_string(str(version['component_version']))}",
        "#endif",
        "",
    ]
    help_lines = [
        f"// Generated by tools/codegen/generate_metadata.py; source-sha256: {digest}.",
        "static const char* const kGeneratedCommandHelp[] = {",
    ]
    for item in commands:
        cli = str(item.get("cli", ""))
        if cli.startswith("facman "):
            help_lines.append(f"    {c_string(cli[len('facman '):])},")
    help_lines.extend(["};", ""])
    top_level = sorted({str(item.get("cli", "")).split()[1] for item in commands if str(item.get("cli", "")).startswith("facman ")})
    words = " ".join(top_level)
    completions = {
        "bash": f"# generated source-sha256: {digest}\ncomplete -W \"{words}\" facman\n",
        "zsh": f"#compdef facman\n# generated source-sha256: {digest}\n_arguments '1:command:({words})'\n",
        "fish": "# generated source-sha256: " + digest + "\n" + "\n".join(f"complete -c facman -f -a {word}" for word in top_level) + "\n",
        "powershell": f"# generated source-sha256: {digest}\nRegister-ArgumentCompleter -Native -CommandName facman -ScriptBlock {{ param($wordToComplete) '{words}'.Split(' ') | Where-Object {{ $_ -like \"$wordToComplete*\" }} }}\n",
    }
    docs = [
        "# Generated Command Catalog",
        "",
        f"Source digest: `{digest}`.",
        "",
        "Do not edit this table directly. Edit the indexed command contracts and regenerate.",
        "",
        "| Contract ID | Runtime ID | Availability | Effects | CLI |",
        "| --- | --- | --- | --- | --- |",
    ]
    for item in commands:
        availability = str(item.get("availability", "available"))
        effects = ", ".join(str(value) for value in item.get("effects", []))
        docs.append(f"| `{item['command_id']}` | `{item['runtime_id']}` | {availability} | {effects} | `{item.get('cli', '')}` |")
    docs.append("")
    return {
        "catalog_json": json.dumps(catalog, indent=2, sort_keys=True) + "\n",
        "command_header": "\n".join(header),
        "version_header": "\n".join(version_header),
        "help_include": "\n".join(help_lines),
        **completions,
        "docs": "\n".join(docs),
    }


def generate(write: bool) -> list[str]:
    index, version, commands, digest = load_sources()
    rendered = render(index, version, commands, digest)
    problems: list[str] = []
    for name, path in OUTPUTS.items():
        expected = rendered[name]
        actual = path.read_text(encoding="utf-8") if path.is_file() else ""
        if actual != expected:
            if write:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(expected, encoding="utf-8")
            else:
                problems.append(f"generated output is stale or missing: {path.relative_to(ROOT).as_posix()}")
    return problems


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate canonical FacMan command and version metadata.")
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    problems = generate(write=args.write)
    if problems:
        for problem in problems:
            print(f"generate-metadata: {problem}", file=sys.stderr)
        return 1
    print("generate-metadata: ok")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
