platform = "windows"

candidate_roots = [
  "%ProgramFiles(x86)%/Steam/steamapps/common/Factorio",
  "%ProgramFiles%/Factorio",
  "%LOCALAPPDATA%/Programs/Factorio",
]

executables = [
  "bin/x64/factorio.exe",
]

