schema = "facman.dependency_lock.v1"
id = "facman_dependency_lock_v1"
lock_kind = "release_time_pinned"
global_runtime_required = false

[[component]]
id = "factorio_binding"
kind = "product_binding"
version = "0.1.0-dev"
abi_version = 1
pin = "2c2cce644b674d12227a194a77bce5a667fed721"
bundled = true
source = "factorio-launcher/runtime/factorio"
install_mutation_authority = false

[[component]]
id = "universal_launcher"
kind = "universal_runtime"
version = "0.1.0-dev"
abi_version = 1
pin = "80a848375227dc858865874ef594c4b466877241"
bundled = true
source = "universal-launcher"
install_mutation_authority = false

[[component]]
id = "universal_setup"
kind = "setup_runtime"
version = "0.1.0-dev"
abi_version = 1
pin = "4855e4f5dd23ae5dfa0d7f23a61ffbf46e1439d2"
bundled = true
source = "universal-setup"
install_mutation_authority = true
