schema = "flaunch.workspace_lock.v1"
id = "facman_workspace_lock_v1"
lock_kind = "public_repository_revisions"
lock_root = "factorio-launcher"

[[component]]
id = "factorio_binding"
source = "factorio-launcher/runtime/factorio"
pin = "2c2cce644b674d12227a194a77bce5a667fed721"
path = "."

[[component]]
id = "universal_launcher"
source = "universal-launcher"
pin = "80a848375227dc858865874ef594c4b466877241"
path = "../universal-launcher"

[[component]]
id = "universal_setup"
source = "universal-setup"
pin = "4855e4f5dd23ae5dfa0d7f23a61ffbf46e1439d2"
path = "../universal-setup"
