# SPDX-FileCopyrightText: 2026 Jules C
# SPDX-License-Identifier: MIT

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
RECIPE = ROOT / "content" / "factorio" / "product" / "factorio.portable-windows-zip.recipe.v1.json"
OUTPUT = (
    ROOT
    / "runtime"
    / "factorio"
    / "install_validation"
    / "generated"
    / "factorio_setup_recipe.inc"
)


def render() -> str:
    value = json.loads(RECIPE.read_text(encoding="utf-8"))
    canonical = json.dumps(value, ensure_ascii=True, sort_keys=True, separators=(",", ":"))
    digest = hashlib.sha256(canonical.encode("utf-8")).hexdigest()
    delimiter = "FACMAN_RECIPE_V1"
    if f"){delimiter}\"" in canonical:
        raise ValueError("recipe collides with generated raw-string delimiter")
    return (
        "// Generated by tools/generate_factorio_setup_recipe.py. Do not edit.\n"
        f'static constexpr const char kFactorioSetupRecipeJson[] = R\"{delimiter}({canonical}){delimiter}\";\n'
        f'static constexpr const char kFactorioSetupRecipeDigest[] = "{digest}";\n'
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    expected = render()
    if args.check:
        if not OUTPUT.is_file() or OUTPUT.read_text(encoding="utf-8") != expected:
            print(f"factorio-setup-recipe: generated file is stale: {OUTPUT.relative_to(ROOT)}")
            return 1
        print("factorio-setup-recipe: generated file is current")
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(expected, encoding="utf-8", newline="\n")
    print(f"factorio-setup-recipe: wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
