# SPDX-FileCopyrightText: 2026 Jules C
# SPDX-License-Identifier: MIT

from __future__ import annotations

import sys
from collections.abc import Callable
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from tools import (  # noqa: E402
    accessibility_human_test_packet_check,
    aide_target_truth_check,
    aide_queue_state_check,
    aide_compaction_check,
    alpha_release_source_check,
    alpha_dev_integration_closeout_check,
    alpha1_tag_truth_closeout_check,
    alpha1_publication_preparation_check,
    alpha1_publication_preparation_closeout_check,
    alpha_portable_test_packet,
    alpha_tag_gate,
    alpha_publication_gate,
    alpha_vertical_slice_check,
    application_handler_check,
    apps_boundary_check,
    archive_core_check,
    branch_policy_check,
    branding_asset_check,
    capability_policy_check,
    critical_io_check,
    ci_proof_check,
    client_cli_boundary_check,
    cmake_architecture_check,
    code_security_check,
    command_contract_check,
    compatibility_corpus_check,
    compliance_check,
    component_ownership_check,
    cross_frontend_journey_conformance,
    diagnostic_export_check,
    discovery_golden_check,
    engineering_quality_check,
    frontend_contract_check,
    frontend_parity_check,
    frontend_transport_truth_check,
    foundation_beta_readiness_check,
    foundation_scope_check,
    factorio_2_1_14_release_route_v4_check,
    factorio_2_1_14_release_route_v5_check,
    factorio_2_1_14_route_d3_d4_request_check,
    factorio_2_1_14_route_packet_check,
    factorio_version_family_check,
    factorio_setup_recipe_check,
    factorio_route_version_decision_check,
    generated_catalog_check,
    gui_surface_check,
    gate4c_privilege_separation_check,
    hermetic_play_policy_check,
    hermetic_play_candidate_check,
    instance_isolated_play_candidate_check,
    instance_lifecycle_check,
    instance_model_check,
    snapshot_lifecycle_check,
    profile_template_check,
    preview_semantic_spine_check,
    language_runtime_policy_check,
    local_lock_check,
    manual_json_check,
    m1_system_proof_check,
    m2_wu9_adversarial_check,
    m2_wu10_machine_acceptance_check,
    m2_wu10_operator_acceptance_check,
    modset_route_check,
    mod_inventory_check,
    modset_solver_check,
    operational_ux_check,
    operation_permit_check,
    save_transfer_route_check,
    save_index_check,
    server_plan_check,
    setup_workflow_check,
    source_closure_admission_check,
    successor_play_route_definition_check,
    package_check,
    package_contract_tck,
    package_layout_check,
    package_manifest_check,
    package_pipeline_check,
    package_skeleton_check,
    provenance_check,
    r37_lifecycle_check,
    refusal_contract_check,
    refusal_golden_check,
    release_contract_check,
    release_identity_coherence_check,
    release_resolution_check,
    release_resolution_integration_check,
    release_programme_check,
    release_structure_check,
    schema_validate,
    security_policy_check,
    source_format_check,
    structure_policy_check,
    strong_id_check,
    synthetic_product_tck_check,
    transaction_recovery_check,
    target_dependency_check,
    technical_preview_census,
    test_architecture_check,
    ui_accessibility_check,
    universal_delivery_programme_check,
    workspace_contract_check,
    workspace_hygiene_check,
    workspace_root_authority_check,
    workspace_resolver_check,
    workspace_store_check,
    windows_classic_profile_check,
    windows_instance_isolated_play_policy_check,
    version_truth_check,
)


def main() -> int:
    checks: list[tuple[str, Callable[[], int]]] = [
        ("aide-target-truth", aide_target_truth_check.main),
        ("aide-queue-state", aide_queue_state_check.main),
        ("aide-compaction", lambda: aide_compaction_check.main([])),
        ("apps-boundary", apps_boundary_check.main),
        ("manual-json", manual_json_check.main),
        ("m1-system-proof", m1_system_proof_check.main),
        ("m2-wu9-adversarial", m2_wu9_adversarial_check.main),
        ("m2-wu10-machine-acceptance-policy", lambda: m2_wu10_machine_acceptance_check.main(["--policy-only"])),
        ("m2-wu10-operator-acceptance", lambda: m2_wu10_operator_acceptance_check.main([])),
        ("critical-io", critical_io_check.main),
        ("generated-catalog", generated_catalog_check.main),
        ("version-truth", version_truth_check.main),
        ("release-identity-coherence", release_identity_coherence_check.main),
        ("alpha-release-source", alpha_release_source_check.main),
        ("alpha-dev-integration-closeout", alpha_dev_integration_closeout_check.main),
        ("alpha1-tag-truth-closeout", alpha1_tag_truth_closeout_check.main),
        (
            "alpha1-publication-preparation",
            lambda: alpha1_publication_preparation_check.main([]),
        ),
        (
            "alpha1-publication-preparation-closeout",
            lambda: alpha1_publication_preparation_closeout_check.main([]),
        ),
        (
            "alpha-portable-test-packet",
            lambda: alpha_portable_test_packet.main(["--check-template"]),
        ),
        ("alpha-tag-policy", alpha_tag_gate.policy_main),
        ("alpha-publication-gate", lambda: alpha_publication_gate.main(["--operation", "qualify"])),
        ("target-dependency", target_dependency_check.main),
        ("test-architecture", test_architecture_check.main),
        ("client-cli-boundary", client_cli_boundary_check.main),
        ("cmake-architecture", cmake_architecture_check.main),
        ("archive-core", archive_core_check.main),
        ("branch-policy", branch_policy_check.main),
        ("branding-assets", branding_asset_check.main),
        ("capability-policy", capability_policy_check.main),
        ("ci-proof", ci_proof_check.main),
        ("code-security", code_security_check.main),
        ("structure", structure_policy_check.main),
        ("strong-id", strong_id_check.main),
        ("synthetic-product-tck", synthetic_product_tck_check.main),
        ("workspace-contract", workspace_contract_check.main),
        ("workspace-hygiene", workspace_hygiene_check.main),
        ("workspace-root-authority", workspace_root_authority_check.main),
        ("workspace-resolver", workspace_resolver_check.main),
        ("workspace-store", workspace_store_check.main),
        ("schema", schema_validate.main),
        ("security", security_policy_check.main),
        ("source-format", source_format_check.main),
        ("ui-accessibility", ui_accessibility_check.main),
        (
            "accessibility-human-test-packet",
            lambda: accessibility_human_test_packet_check.main([]),
        ),
        ("package", package_check.main),
        ("package-contract-tck", lambda: package_contract_tck.main([])),
        ("package-layout", package_layout_check.main),
        ("package-manifest", package_manifest_check.main),
        ("package-pipeline", package_pipeline_check.main),
        ("package-skeleton", package_skeleton_check.main),
        ("provenance", provenance_check.main),
        ("release-programme", release_programme_check.main),
        ("technical-preview-census", lambda: technical_preview_census.main(["--check"])),
        ("gui-surface", gui_surface_check.main),
        ("gate4c-privilege-separation", gate4c_privilege_separation_check.main),
        ("hermetic-play-policy", hermetic_play_policy_check.main),
        (
            "windows-instance-isolated-play-policy",
            windows_instance_isolated_play_policy_check.main,
        ),
        ("hermetic-play-candidate", hermetic_play_candidate_check.main),
        (
            "instance-isolated-play-candidate",
            instance_isolated_play_candidate_check.main,
        ),
        ("instance-lifecycle", instance_lifecycle_check.main),
        ("instance-model", instance_model_check.main),
        ("snapshot-lifecycle", snapshot_lifecycle_check.main),
        ("profile-template", profile_template_check.main),
        ("preview-semantic-spine", preview_semantic_spine_check.main),
        ("language-runtime-policy", language_runtime_policy_check.main),
        ("local-lock", local_lock_check.main),
        ("modset-route", modset_route_check.main),
        ("mod-inventory", mod_inventory_check.main),
        ("modset-solver", modset_solver_check.main),
        ("save-transfer-route", save_transfer_route_check.main),
        ("save-index", save_index_check.main),
        ("server-plan", server_plan_check.main),
        ("setup-workflow", setup_workflow_check.main),
        ("source-closure-admission", source_closure_admission_check.main),
        ("successor-play-route-definition", successor_play_route_definition_check.main),
        ("operational-ux", operational_ux_check.main),
        ("operation-permit", operation_permit_check.main),
        ("r37-lifecycle", r37_lifecycle_check.main),
        ("transaction-recovery", transaction_recovery_check.main),
        ("diagnostic-export", diagnostic_export_check.main),
        ("command-contract", command_contract_check.main),
        ("compatibility-corpus", compatibility_corpus_check.main),
        ("component-ownership", component_ownership_check.main),
        ("cross-frontend-journey-conformance", cross_frontend_journey_conformance.main),
        ("compliance", compliance_check.main),
        ("frontend-contract", frontend_contract_check.main),
        ("frontend-parity", frontend_parity_check.main),
        ("frontend-transport-truth", frontend_transport_truth_check.main),
        ("foundation-scope", foundation_scope_check.main),
        ("foundation-beta-readiness", foundation_beta_readiness_check.main),
        ("engineering-quality", engineering_quality_check.main),
        ("factorio-setup-recipe", factorio_setup_recipe_check.main),
        ("factorio-2-1-14-release-route-v4-historical", factorio_2_1_14_release_route_v4_check.main),
        ("factorio-2-1-14-release-route", factorio_2_1_14_release_route_v5_check.main),
        (
            "factorio-2-1-14-route-d3-d4-request",
            factorio_2_1_14_route_d3_d4_request_check.main,
        ),
        ("factorio-2-1-14-route-packet", factorio_2_1_14_route_packet_check.main),
        ("factorio-route-version-decision", factorio_route_version_decision_check.main),
        ("factorio-version-family", lambda: factorio_version_family_check.main([])),
        ("alpha-vertical-slice", alpha_vertical_slice_check.main),
        ("application-handler", application_handler_check.main),
        ("refusal-contract", refusal_contract_check.main),
        ("refusal-golden", refusal_golden_check.main),
        ("discovery-golden", discovery_golden_check.main),
        ("release-structure", release_structure_check.main),
        ("release-contract", release_contract_check.main),
        ("release-resolution", release_resolution_check.main),
        ("release-resolution-integration", release_resolution_integration_check.main),
        ("universal-delivery-programme", universal_delivery_programme_check.main),
        ("windows-classic-profile", windows_classic_profile_check.main),
    ]
    failed: list[str] = []
    for name, check in checks:
        if check() != 0:
            failed.append(name)
    if failed:
        print(f"strict-check: failed checks: {', '.join(failed)}", file=sys.stderr)
        return 1
    print("strict-check: ok")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
