add_library(facman_warnings INTERFACE)
add_library(facman_hardening INTERFACE)
add_library(facman_sanitizers INTERFACE)
add_library(facman_coverage INTERFACE)

if(MSVC)
  target_compile_options(facman_warnings INTERFACE /W4)
  target_compile_options(facman_hardening INTERFACE /guard:cf)
  target_link_options(facman_hardening INTERFACE /guard:cf /DYNAMICBASE)
  if(FACMAN_WARNINGS_AS_ERRORS)
    target_compile_options(facman_warnings INTERFACE /WX)
  endif()
else()
  target_compile_options(facman_warnings INTERFACE -Wall -Wextra -Wpedantic)
  target_compile_options(facman_hardening INTERFACE -fstack-protector-strong)
  if(FACMAN_WARNINGS_AS_ERRORS)
    target_compile_options(facman_warnings INTERFACE -Werror)
  endif()
  if(FACMAN_ENABLE_SANITIZERS)
    target_compile_options(facman_sanitizers INTERFACE -fsanitize=address,undefined -fno-omit-frame-pointer)
    target_link_options(facman_sanitizers INTERFACE -fsanitize=address,undefined)
  endif()
  if(FACMAN_ENABLE_COVERAGE)
    target_compile_options(facman_coverage INTERFACE --coverage)
    target_link_options(facman_coverage INTERFACE --coverage)
  endif()
endif()

function(facman_apply_policies target)
  target_link_libraries(${target} PRIVATE facman_warnings facman_hardening facman_sanitizers facman_coverage)
endfunction()
