set(_facman_cli_default ON)
set(_facman_tests_default ON)
set(_facman_sanitizers_default OFF)
set(_facman_tui_default OFF)
set(_facman_daemon_default OFF)
if(DEFINED FLAUNCH_BUILD_NATIVE_APPS)
  set(_facman_cli_default ${FLAUNCH_BUILD_NATIVE_APPS})
endif()
if(DEFINED FLAUNCH_BUILD_TESTS)
  set(_facman_tests_default ${FLAUNCH_BUILD_TESTS})
endif()
if(DEFINED FLAUNCH_ENABLE_SANITIZERS)
  set(_facman_sanitizers_default ${FLAUNCH_ENABLE_SANITIZERS})
endif()
if(DEFINED FACMAN_BUILD_EXPERIMENTAL_FRONTENDS AND FACMAN_BUILD_EXPERIMENTAL_FRONTENDS)
  set(_facman_tui_default ON)
  set(_facman_daemon_default ON)
endif()

option(FACMAN_BUILD_CLI "Build the native FacMan CLI" ${_facman_cli_default})
option(FACMAN_BUILD_TUI "Build the experimental TUI" ${_facman_tui_default})
option(FACMAN_BUILD_DAEMON "Build the experimental daemon" ${_facman_daemon_default})
option(FACMAN_BUILD_GUI "Build platform GUI targets when available" OFF)
option(FACMAN_BUILD_TESTS "Build native tests" ${_facman_tests_default})
option(FACMAN_WITH_SETUP "Enable Universal Setup-backed operations" ON)
option(FACMAN_ENABLE_SANITIZERS "Enable ASan and UBSan" ${_facman_sanitizers_default})
option(FACMAN_ENABLE_COVERAGE "Enable compiler coverage instrumentation" OFF)
option(FACMAN_WARNINGS_AS_ERRORS "Treat first-party compiler warnings as errors" OFF)
option(FACMAN_ENABLE_CLANG_TIDY "Run clang-tidy through CMake on first-party targets" OFF)
option(FACMAN_ENABLE_LIBFUZZER "Build bounded libFuzzer targets with Clang" OFF)

set(FLAUNCH_BUILD_NATIVE_APPS ${FACMAN_BUILD_CLI} CACHE BOOL "Compatibility alias for FACMAN_BUILD_CLI" FORCE)
set(FLAUNCH_BUILD_TESTS ${FACMAN_BUILD_TESTS} CACHE BOOL "Compatibility alias for FACMAN_BUILD_TESTS" FORCE)
set(FLAUNCH_ENABLE_SANITIZERS ${FACMAN_ENABLE_SANITIZERS} CACHE BOOL "Compatibility alias for FACMAN_ENABLE_SANITIZERS" FORCE)
set(FACMAN_BUILD_EXPERIMENTAL_FRONTENDS OFF CACHE BOOL "Compatibility aggregate for experimental frontends" FORCE)
if(FACMAN_BUILD_TUI OR FACMAN_BUILD_DAEMON)
  set(FACMAN_BUILD_EXPERIMENTAL_FRONTENDS ON CACHE BOOL "Compatibility aggregate for experimental frontends" FORCE)
endif()
